### ISSUE TITLE
Unable to switch lyrics properly 

### ISSUE THREAD

**Issue by Its-Tony** [fast4x/RiMusic#2608] opened 2024-07-03 02:28 UTC
### Steps to reproduce the bug

1. Toggle lyrics
2. Synced lyrics keeping loading 
3. Tap unsync lyrics
4. Unsynced lyrics loaded 
5. Tap sync lyrics again

### Expected behavior

On tapping lyrics it should show lyrics

### Actual behavior

On tapping lyrics it should show lyrics and but it keeps loading them(synced one) infinitely. if we tap unsync lyrics it load them quickly but we are unable to switch to synced lyrics again. 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/172184183/577c07ad-0b56-4a8e-9655-bbeee0ad9a70

### RiMusic version

0.6.41

### Android version

Android 11

### Additional information

In Video, I have shown you that LRCLIB have only synced lyrics for same track.

**Comment by faustaahmad** [comment] 2024-07-03 06:25
Duplicate #2552

**Comment by fast4x** [comment] 2024-07-03 07:33
Occur with all songs?

**Comment by faustaahmad** [comment] 2024-07-03 08:31
> Occur with all songs?

Seems to occur to songs that has synchronized lyrics found in KuGou.com
Cant switch to unsynchronized lyrics

**Comment by aneesh1122** [comment] 2024-07-03 08:51
> ### Steps to reproduce the bug
> 1. Toggle lyrics
> 2. Synced lyrics keeping loading
> 3. Tap unsync lyrics
> 4. Unsynced lyrics loaded
> 5. Tap sync lyrics again
> 
> ### Expected behavior
> On tapping lyrics it should show lyrics
> 
> ### Actual behavior
> On tapping lyrics it should show lyrics and but it keeps loading them(synced one) infinitely. if we tap unsync lyrics it load them quickly but we are unable to switch to synced lyrics again.
> 
> ### Screenshots/Screen recordings
>  Screenrecorder-2024-07-03-07-41-32-484.2.mp4 
> ### Logs
> _No response_
> 
> ### RiMusic version
> 0.6.41
> 
> ### Android version
> Android 11
> 
> ### Additional information
> In Video, I have shown you that LRCLIB have only synced lyrics for same track.

off topic but why are you not using new lyrics layout? have you tried it yet?

**Comment by Its-Tony** [comment] 2024-07-03 09:13
@fast4x I have checked again it is happening in most songs you can't switch between synced and unsynced lyrics. If a song shows synced lyrics and you tap unsynced same problem happen. It load for sometime and fallback to synced one.

**Comment by Its-Tony** [comment] 2024-07-03 09:23
@aneesh1122 I've enabled that now and it look good. Kudos for your hard work. BTW how you enabled song cover as background to whole screen? Would love if it can show song cover in full screen.

**Comment by aneesh1122** [comment] 2024-07-03 09:56
> @aneesh1122 I've enabled that now and it look good. Kudos for your hard work. BTW how you enabled song cover as background to whole screen? Would love if it can show song cover in full screen.

https://github.com/fast4x/RiMusic/assets/45353488/75bebb50-5383-4607-bc30-96e4a23b4f57

**Comment by Its-Tony** [comment] 2024-07-03 11:19
@aneesh1122 add some darkness to lyrics background,if there is white colour in background lyrics are barely readable.

**Comment by aneesh1122** [comment] 2024-07-03 11:36
> @aneesh1122 add some darkness to lyrics background,if there is white colour in background lyrics are barely readable.

Use outline

Or

use Lyrics color -> accent

I've already blurred the background when lyrics are enabled to Increase the visibility

which song are you listening to? Let me try

**Comment by fast4x** [comment] 2024-07-04 07:11
Not reproduced, maybe it occur with specific lyrics songs...

**Comment by faustaahmad** [comment] 2024-07-04 08:25
> Not reproduced, maybe it occur with specific lyrics songs...

https://music.youtube.com/watch?v=qvP6kyURSDk (song above)
No sync lyrics even if I changed the title too (usually can nail it)

Try this? *switch unsync & sync lyrics*
https://music.youtube.com/watch?v=JinmeJ92uo0 (bugged, KuGou)
https://music.youtube.com/watch?v=6uNc8GNqza4 (fine, LrcLib)
https://music.youtube.com/watch?v=_2o_zbJcnE0 (bugged, KuGou)

> Should I made new issue for this? *bug*
Since if lyrics doesnt found, then couldnt switch to it (between unsync & sync like in the past)
So, user couldnt create their own custom lyrics anymore on __both__ unsync & sync lyrics
Sorry if I couldnt explain it better
・Past: click switch to sync/unsync → switch even though no lyrics (can edit)
・Current: click switch to sync/unsync → only switch if lyrics found, else stay on first lyrics found (if no lyrics then no lyrics)

**Comment by fast4x** [comment] 2024-07-04 10:45
ok

**Comment by fast4x** [comment] 2024-07-04 15:59
I think is fixed now, available from version 0.6.42

**Comment by Its-Tony** [comment] 2024-07-05 03:46
@fast4x Can we have these tabs in RiMusic ?
![IMG_20240705_091419](https://github.com/fast4x/RiMusic/assets/172184183/4a23461b-20fb-475e-8d2e-b0c2fc71ea03)

**Comment by fast4x** [comment] 2024-07-05 05:47
No, RiMusic doesn’t have to have them just because it has another application.

**Closed** 2024-07-05 21:46 UTC
Labels: bug, Fixed
