### ISSUE TITLE
Next song button bug

### ISSUE THREAD

**Issue by kris20030705** [fast4x/RiMusic#3340] opened 2024-08-21 06:37 UTC
### Steps to reproduce the bug

After latest version, Next button is recognizing as previous song sometimes..!
using inbuilt player seems works fine but earphone or earbuds to next song has bug

### Expected behavior

To properly next song while screen is locked and using earphone and earbuds

### Actual behavior

Even if i nexting songs instead its repeat same song or previous song

### RiMusic version

6.48

### Android version

13

**Comment by twistios** [comment] 2024-08-21 07:03
Same problem sometimes within notification.

**Comment by kris20030705** [comment] 2024-08-21 07:06
> Same problem sometimes within notification.

Glad i am not the only one..!

**Comment by aneesh1122** [comment] 2024-08-21 07:52
Are you using the modern player?

**Comment by twistios** [comment] 2024-08-21 08:33
Yes.

**Comment by aneesh1122** [comment] 2024-08-21 08:44
Many people are having this problem but @fast4x still can't reproduce this bug and it can't be fixed until he can find this bug in his device.

**Comment by fast4x** [comment] 2024-08-21 09:51
Unfortunately I can’t reproduce the problem, but I keep trying to reproduce it and solve it. It will be a nonsense I’m almost sure.

**Comment by aneesh1122** [comment] 2024-08-21 09:53
> Unfortunately I can’t reproduce the problem, but I keep trying to reproduce it and solve it. It will be a nonsense I’m almost sure.

Could you please post a video of what you're doing exactly?

Pls skip until the 14th song. Sometimes the  problem occurs after the 13th song.

**Comment by fast4x** [comment] 2024-08-21 09:56
Yes, as soon as I can do it.

**Comment by kris20030705** [comment] 2024-08-21 10:03
> Unfortunately I can’t reproduce the problem, but I keep trying to reproduce it and solve it. It will be a nonsense I’m almost sure.


https://github.com/user-attachments/assets/ef5408c1-ce0c-405d-ab7c-dc787b42a243

![Screenshot_20240821-154717_RiMusic](https://github.com/user-attachments/assets/cbd3bd90-c3cd-488c-a820-ea662e604472)

**Comment by fast4x** [comment] 2024-08-21 10:09
Yes of course, I'll try again with many conditions.

**Comment by aneesh1122** [comment] 2024-08-21 10:09
> > Unfortunately I can’t reproduce the problem, but I keep trying to reproduce it and solve it. It will be a nonsense I’m almost sure.
> 
> I am pressing next button only @fast4x 
> 
> https://github.com/user-attachments/assets/ef5408c1-ce0c-405d-ab7c-dc787b42a243
> 
> This is queue 
> 
> ![Screenshot_20240821-154717_RiMusic](https://github.com/user-attachments/assets/cbd3bd90-c3cd-488c-a820-ea662e604472)
> 

> Are you using the modern player?

**Comment by fast4x** [comment] 2024-08-21 10:10
You press next button from earphones?

**Comment by kris20030705** [comment] 2024-08-21 10:17
> You press next button from earphones?

My phone was feature to next song using volume but i swear thats not the problem..its same with earphone and earbuds.!

**Comment by kris20030705** [comment] 2024-08-21 10:20
@aneesh1122 essential player works fine..!
Btw why swiping ablum art to next song has better animation than pressing next song button??? @fast4x 

https://github.com/user-attachments/assets/0a938089-68c4-4a35-b64f-a89fdc5b40e1

**Comment by aneesh1122** [comment] 2024-08-21 10:26
> @aneesh1122 essential player works fine..!
> Btw why swiping ablum art to next song has better animation than pressing next song button??? @fast4x 
> You can see on this video..!
> 
> https://github.com/user-attachments/assets/0a938089-68c4-4a35-b64f-a89fdc5b40e1
> 
> 

That's strange. Animation works fine in my device

https://github.com/user-attachments/assets/3a888229-1bde-4787-9655-35a4ccafbc2c

**Comment by aneesh1122** [comment] 2024-08-21 10:28
> essential player works fine

See, here the problem is with modern player only. Maybe the behaviour is different but I'm sure the root problem is the same.

@fast4x

**Comment by kris20030705** [comment] 2024-08-21 10:42
> > essential player works fine
> 
> See, here the problem is with modern player only. Maybe the behaviour is different but I'm sure the root problem is the same.
> 
> @fast4x

My bad..!
I though inbuilt music player is essential 
I forgot there is modern and Essential..!
Let me change the setting..!

**Comment by fast4x** [comment] 2024-08-21 10:47
I still don’t understand, the type of player has nothing to do with changing the song from headphones because in that case it is managed by the service and not by the type of player.

**Comment by kris20030705** [comment] 2024-08-21 10:47
> > essential player works fine
> 
> See, here the problem is with modern player only. Maybe the behaviour is different but I'm sure the root problem is the same.
> 
> @fast4x

Ohh yeah it is..!

**Comment by kris20030705** [comment] 2024-08-21 10:49
> I still don’t understand, the type of player has nothing to do with changing the song from headphones because in that case it is managed by the service and not by the type of player.

Put player to modern and
Lock the screen and next song from lock screen..!

**Comment by fast4x** [comment] 2024-08-21 10:55
When screen is locked, actions are managed by the service, not by player...

**Comment by kris20030705** [comment] 2024-08-21 10:57
> When screen is locked, actions are managed by the service, not by player...

But working fine in essential player

**Comment by aneesh1122** [comment] 2024-08-21 10:57
> When screen is locked, actions are managed by the service, not by player...

And when the player is put in the background?

**Comment by kris20030705** [comment] 2024-08-21 11:03
@fast4x its same..!
Yeah problem is with modern player

Uploading screen-20240821-164646.mp4…

**Comment by kris20030705** [comment] 2024-08-21 11:04
@fast4x same without locking phone
Problem is with modern player


https://github.com/user-attachments/assets/2e7eefde-025e-42a3-a3a1-3f9438d5b4a7

**Comment by fast4x** [comment] 2024-08-21 11:05
Let me see what you mean by essential player

**Comment by aneesh1122** [comment] 2024-08-21 11:07
> Let me see what you mean by essential player

![Screenshot_2024-08-21-16-36-44-270_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/77d82d14-490a-4788-b960-2ed95fddb521)

**Comment by fast4x** [comment] 2024-08-21 11:21
Player type isn't related to action issue in background player.

**Comment by aneesh1122** [comment] 2024-08-21 11:37
> Player type isn't related to action issue in background player.

I'm using a Xiaomi device and he's using a Nothing device. Which company's device are you using?

If you're still not getting this bug then please post a video of what you're doing.

**Comment by fast4x** [comment] 2024-08-21 11:59
Maybe reproduced it occur when app ho in the background with player opened... if player is minimized, it work.

**Comment by fast4x** [comment] 2024-08-21 12:01
> > Player type isn't related to action issue in background player.
> 
> I'm using a Xiaomi device and I think he's using a Nothing device. Which company's device are you using?
> 
> If you're still not getting this bug then please post a video of what you're doing
> 
> Do exactly this
> 
> https://github.com/user-attachments/assets/216d5755-c52e-49b5-9996-202bd2488048

Also i'ha Xiaomi device

**Comment by aneesh1122** [comment] 2024-08-21 12:04
> Maybe reproduced it occur when app go in the background with player opened... if player is minimized, it work.

Yeah it works perfectly if the player is minimized first

**Comment by fast4x** [comment] 2024-08-21 17:58
I think is fixed now, i'm building a custom to try...

**Comment by fast4x** [comment] 2024-08-21 18:15
Custom ready to download
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by aneesh1122** [comment] 2024-08-21 18:25
> Custom ready to download
> https://github.com/fast4x/RiMusic/tree/master/customVersion

IT'S FIXED 🎉

**Comment by fast4x** [comment] 2024-08-21 18:26
@aneesh1122 AMAAAAAZIIIIINGGGGGGGG

**Comment by fast4x** [comment] 2024-08-21 18:27
@kris20030705 try changing from headphones please

**Comment by fast4x** [comment] 2024-08-21 19:52
I make this as fixed, available from version 0.6.49

**Closed** 2024-08-23 20:12 UTC
Labels: bug, Fixed
