### ISSUE TITLE
Playback stopped while on phone call?

### ISSUE THREAD

**Issue by bubin7766** [fast4x/RiMusic#3458] opened 2024-08-28 12:00 UTC
### Steps to reproduce the bug

1. Start/Answer a phone call
2. Attempt to play either downloaded or searched music
3. Listen to the sweet sound of nothing

### Expected behavior

You would expect it to play the music since that's imo a core feature of android
I have tested this with stock music apps as well and music plays just fine there, even with patched YT Music

### Actual behavior

No music is played and instead you just see the play button do a little spin :)

### RiMusic version

0.6.49.2

### Android version

Android 14, One UI 6.1

### Additional information

I have made sure battery and background optimizations are disabled as well

**Comment by fast4x** [comment] 2024-08-28 13:51
Explain better please

**Comment by bubin7766** [comment] 2024-08-28 13:56
Quite simply music can not be played if the user is currently on a phone call when the expected behavior is that music should play while on a phone call
Not sure if this is a limitation of the app as the only other app I've seen repeat this behavior is Pandora
Spotify, YT Music, and Poweramp work fine with playing music while on a phone call meanwhile Rimusic does not

**Comment by Simon-Sonnleitner** [comment] 2024-08-28 14:17
I think this is a duplicate of https://github.com/fast4x/RiMusic/issues/1632

**Comment by fast4x** [comment] 2024-08-28 18:49
It's normal, during call, music is paused.

**Comment by fast4x** [comment] 2024-08-28 18:50
> I think this is a duplicate of https://github.com/fast4x/RiMusic/issues/1632

not the same...

**Closed** 2024-08-30 21:09 UTC
Labels: bug, support
