### ISSUE TITLE
App crashes whenever i try to move songs in que

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#3412] opened 2024-08-25 17:03 UTC
### Steps to reproduce the bug

 .

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

.

### Logs

.

### RiMusic version

.

### Android version

.

### Additional information

.

**Comment by twistios** [comment] 2024-08-25 17:19
Duplicate of #3403.

**Comment by fast4x** [comment] 2024-08-27 07:36
Fixed available from version 0.6.50

**Closed** 2024-08-30 21:07 UTC
Labels: bug, Fixed
