### ISSUE TITLE
Player open close animation disappears when disable swiping down is enabled

### ISSUE THREAD

**Issue by 821938089** [fast4x/RiMusic#1053] opened 2024-03-14 03:10 UTC
### Steps to reproduce the bug

Look video

### Expected behavior

working

### Actual behavior

not working

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/8674809/71dc2e78-f98a-4e6f-8910-671be1341fdb

### RiMusic version

0.6.25

### Android version

Android 14

### Additional information

switching this option on and off will make the UI stop responding

**Comment by Nikks84** [comment] 2024-03-14 04:04
The option is not for what you are thinking, this option works when the player is minimize it works then and it is not a bug, it is expected behavior.

**Comment by dAtA-TRoN** [comment] 2024-03-14 04:38
It's about being able to swipe down on the minimized player to close it. This option allows you to toggle that behavior on or off.

**Comment by 821938089** [comment] 2024-03-14 05:30
However, this option causes problems with the player's unfolding and retracting animations.

You may have misunderstood me, but what I was trying to say is clearly shown in the video. Sorry I'm not a native English speaker, I'm using a translator to communicate with you.

**Comment by dAtA-TRoN** [comment] 2024-03-14 05:36
@821938089 

No problem, but it's not so entirely clear from that video, as you think.
What I see is that you're swiping the player up to show that it's possible before toggling the switch. Then you do the same thing again. And that's completely normal and intended behavior of the app. The setting specifically refers to the ability to swipe the already minimized player down again to close it. If there's something I'm still not understanding, please explain it more clearly.

**Comment by 821938089** [comment] 2024-03-14 07:32
@dAtA-TRoN What I mean is that when I expand the player, I slide my finger upwards but no animation appears, when I close the option the animation is displayed normally.

https://github.com/fast4x/RiMusic/assets/8674809/19b095eb-2e21-404b-901a-60aea077bd97

**Comment by dAtA-TRoN** [comment] 2024-03-14 07:40
@821938089 

#1021

Oh, well, that has already been addressed. Again: before you post anything here, please make sure to check if it has already been posted, as it could otherwise become confusing. And once again: Please remove all your posts that are now obsolete.

**Comment by 821938089** [comment] 2024-03-14 07:48
The point is not the delay of the switch, it's the unfolding and retracting animation of the player.
I have checked this issue and it has nothing to do with this main issue.

**Comment by dAtA-TRoN** [comment] 2024-03-14 08:22
> The point is not the delay of the switch, it's the unfolding and retracting animation of the player.
> I have checked this issue and it has nothing to do with this main issue.

Alright, in your latest video, things were much clearer. Your detailed explanation certainly helped in understanding you better. Fast4x should definitely give it a watch. Moving forward, try to be a bit more precise in articulating your points. As a helpful tip: ChatGPT is an excellent resource for assistance. I rely on it almost exclusively for translating or refining my queries.

**Comment by fast4x** [comment] 2024-03-14 16:54
Yes, I understood the report, the problem is the sliding effect, I check if I can keep it even with swipe down disabled on the miniplayer.

**Comment by fast4x** [comment] 2024-04-05 14:46
Improved, available from version 0.6.29

**Closed** 2024-04-05 20:57 UTC
Labels: bug, Fixed
