### ISSUE TITLE
Changing play order crashes the app

### ISSUE THREAD

**Issue by Gighuffer** [fast4x/RiMusic#3462] opened 2024-08-28 16:32 UTC
### Steps to reproduce the bug

Go to queue
Hold on the three horizontal bars and drag the song above the previous in queue

### Expected behavior

The song is moved to a different place in the queue

### Actual behavior

The app crashes

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/d3655b47-440f-4a81-bb75-ca6dbbca74c7

### Logs

2024-08-28T13:30:12.837:	java.lang.NoSuchMethodError: No virtual method removeFirst()Ljava/lang/Object; in class Ljava/util/ArrayList; or its super classes (declaration of 'java.util.ArrayList' appears in /apex/com.android.art/javalib/core-oj.jar)
	 V5.a.a(SourceFile:1) 
	 A1.d.b(SourceFile:90) 
	 V5.i.u(SourceFile:101) 
	 g7.a.i(SourceFile:9) 
	 z7.J.run(SourceFile:113) 
	 J0.d0.h0(SourceFile:7) 
	 J0.c0.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1069) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

### RiMusic version

V0.6.49.2

### Android version

Android 14

**Comment by twistios** [comment] 2024-08-28 16:53
Duplicate of #3403.
The fix will be available from next version 0.6.50.

**Closed** 2024-08-30 21:07 UTC
Labels: bug, Fixed
