### ISSUE TITLE
error when viewing an album

### ISSUE THREAD

**Issue by Dani3l9765** [fast4x/RiMusic#2421] opened 2024-06-22 13:44 UTC
### Steps to reproduce the bug

1. Go to any album
2. See error

### Expected behavior

It should show you the songs from the album.

### Actual behavior

When entering an album, whether from the recommendations or an album that I searched for on my own, the songs simply do not appear, nor does it load the album cover.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/150991300/66d11664-5a5f-4044-8969-085a4aa4c8f5

### RiMusic version

0.6.40

### Android version

Android 13

**Comment by twistios** [comment] 2024-06-22 15:27
Duplicate of https://github.com/fast4x/RiMusic/issues/2388.
The problem is because of an api-change in youtube. fast4x already knows about the problem and is working on a fix.

**Comment by fast4x** [comment] 2024-06-24 07:53
Fixed, available today from version 0.6.40.1

**Closed** 2024-06-24 10:48 UTC
Labels: bug, Fixed
