### ISSUE TITLE
in albums it does not load the song lists

### ISSUE THREAD

**Issue by obitopy** [fast4x/RiMusic#2422] opened 2024-06-22 13:59 UTC
### Steps to reproduce the bug

![Screenshot_2024-06-22-09-57-45-182_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/173553435/76b8efcd-02fd-43a0-9bda-f73065aadd33)

### Expected behavior

first time

### Actual behavior

first time

### Screenshots/Screen recordings

![Screenshot_2024-06-22-09-57-45-182_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/173553435/349c00a3-fb62-4dec-9457-5c11e091c206)

### Logs

![Screenshot_2024-06-22-09-57-45-182_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/173553435/f7ff1284-4107-4ce2-b602-c7b90d94bc7d)

### RiMusic version

v0.6.40

### Android version

Android 13

### Additional information

In all versions I get the same problem

**Comment by twistios** [comment] 2024-06-22 15:25
Duplicate of #2388. 
The problem is because of an api-change in youtube. fast4x already knows about the problem and is working on a fix.

**Comment by fast4x** [comment] 2024-06-24 07:53
Fixed, available today from version 0.6.40.1

**Closed** 2024-06-24 10:48 UTC
Labels: bug, Fixed
