### ISSUE TITLE
Albums are no longer displayed or take a long time to load.

### ISSUE THREAD

**Issue by StarlinatorGL** [fast4x/RiMusic#2395] opened 2024-06-21 20:37 UTC
### Steps to reproduce the bug

Go to the saved albums or search for them.

### Expected behavior

The list of songs contained in the albums should have been displayed.

### Actual behavior

Songs are not displayed in the albums.

### Screenshots/Screen recordings

![Screenshot_20240621-133553](https://github.com/fast4x/RiMusic/assets/158228234/68fe8a57-cbac-46c7-8885-256f3e051600)

### RiMusic version

0.6.39

### Android version

Android 12

**Comment by KOLIWAN** [comment] 2024-06-21 22:37
Duplicate of #2390 
Anyway, annoying bug 😭

**Comment by twistios** [comment] 2024-06-22 01:08
It is #2388 actually.

**Comment by fast4x** [comment] 2024-06-22 06:55
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

**Comment by fast4x** [comment] 2024-06-24 07:56
Fixed, available today from version 0.6.40.1

**Comment by StarlinatorGL** [comment] 2024-06-24 08:09
Great, thank you very much for taking the guy to correct it. I will wait
for the update to F-Droid to arrive.

**Closed** 2024-06-24 10:48 UTC
Labels: bug, Fixed
