### ISSUE TITLE
Statistics don't track properly

### ISSUE THREAD

**Issue by Carter0108** [fast4x/RiMusic#2082] opened 2024-05-28 21:23 UTC
### Steps to reproduce the bug

View statistics for any period of time.

### Expected behavior

Should track your most played songs, artists, albums.

### Actual behavior

Simply displays the most recent 10 played songs as top played song, artist and album regardless of how many times they've actually been played.

### RiMusic version

0.6.36.1

### Android version

Android 14

**Comment by fast4x** [comment] 2024-05-28 22:16
What exactly do you think it should show?

**Comment by JeePopuwu** [comment] 2024-05-29 00:03
> ¿Qué crees exactamente que debería mostrar?

I think that what is meant that should be shown are the most reproduced ones.  of the week, of the month, I mean not random, that there was an algorithm that gives the most reproduced ones, or well, that's what I think x,d

**Comment by Carter0108** [comment] 2024-05-29 05:54
> What exactly do you think it should show?

Should it not be the most played songs of that given time period? Currently, any new song I listen to will jump straight to my number one most played song despite it being the first time hearing it.

**Comment by AquamarineDreams** [comment] 2024-05-29 15:23
Duplicate of #1449 

@Carter0108 @fast4x

**Closed** 2024-06-09 16:19 UTC
Labels: bug
