### ISSUE TITLE
[Feature]: Predictive back

### ISSUE THREAD

**Issue by Moodzz1** [fast4x/RiMusic#618] opened 2024-02-05 23:52 UTC
### Description

Add support for android 14 (13?) predictive back gesture.

### Suggested Solution

N/A

**Comment by fast4x** [comment] 2024-02-06 15:48
It’s already been implemented, what’s missing is animation.

**Comment by Quinxxxx** [comment] 2024-02-06 18:01
Can you add the missing animation? Would be appreciated.

**Comment by Jak2k** [comment] 2024-05-27 15:09
Dupe of #198

**Comment by OrangeZXZ** [comment] 2024-12-02 00:47
@fast4x i think this one can be closed (because we have the animations)

**Comment by fast4x** [comment] 2024-12-02 06:40
yep

**Closed** 2024-12-13 22:34 UTC
Labels: enhancement, Idea, Already implemented
