### ISSUE TITLE
queue is off after some time

### ISSUE THREAD

**Issue by enomao44** [fast4x/RiMusic#4590] opened 2024-11-21 07:41 UTC
### Description

not sure if this is how should be working or is failing but when i prepare a queue and is there for some time idk suddenly after 2 days or so the queue is not there anymore and i didnt finish it to listen it. is the queue saving the data with some kind of limit of time and then disappers?? it happened to me different times. 

### Suggested Solution

long limit or no limit

**Comment by Tre916** [comment] 2024-11-22 00:27
I've noticed the queue clearing/disappearing after hours not even days. It used to be one thing I could count on in this app, that it would keep the queue active. This is very important, it's one of the reasons I stopped using the YouTube Music app itself.

**Comment by enomao44** [comment] 2024-11-22 05:25
when i use deezer the queue remains there even after so many days and time no using the app. would be very good even when they launch the desktop version that the queues on the pc and the phone are linked also.

**Comment by fast4x** [comment] 2024-11-22 15:30
I think was a bug and it's now fixed. Available from version 0.6.61

**Comment by enomao44** [comment] 2024-11-22 16:15
so the real feature here which one is it? no limit time on the queue to keep it?

**Comment by fast4x** [comment] 2024-11-22 19:29
There isn't a reason that clean queue, i think was caused by a bug in saving songs.

**Closed** 2024-11-22 23:10 UTC
Labels: bug, Fixed
