### ISSUE TITLE
Arrow button not working..!

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1414] opened 2024-04-06 20:06 UTC
### Steps to reproduce the bug

Arrow button not working after new update..!
Dunno if it is only for me..?

### Expected behavior

To show songs in queue..!

### Actual behavior

Not opening..

### Screenshots/Screen recordings

![Screenshot_20240407-014800_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/801fa8f6-6c89-42c4-b883-b3e35617209a)

### RiMusic version

0.6.29

### Android version

Android 13

**Comment by dAtA-TRoN** [comment] 2024-04-06 20:53
Yeah, it's a recognized issue. Until the next update, we should just stick to disabling the arrow key and using the swipe gesture instead.

**Comment by AquamarineDreams** [comment] 2024-04-08 00:58
Duplicate of #1383 and #1385

**Comment by faustaahmad** [comment] 2024-04-08 09:20
Why enabling arrow up button disable the swipe up gesture, very bad QoL smh

**Comment by dAtA-TRoN** [comment] 2024-04-08 09:31
> Why enabling arrow up button disable the swipe up gesture, very bad QoL smh

To reduce redundancy. Why do you need two different input methods for the same thing?

**Comment by faustaahmad** [comment] 2024-04-08 09:57
> To reduce redundancy. Why do you need two different input methods for the same thing?
I like to swipe up, but I often use that button too (which both cosmetic & usable)

It's not redundant at all

If I disable that arrow up button, my player looks wierd with only 2 button
Also when my relative use the app, sometimes they forgot that swipe up exist (even if it's just a cosmetic, still hold value as tips/clue)

**Comment by dAtA-TRoN** [comment] 2024-04-08 10:01
~~> sometimes they forgot that swipe up exist

Is that so? Typically, you wouldn't forget it because the pill symbol appears when you disable the arrow button, reminding you to use the gesture.

**Comment by fast4x** [comment] 2024-04-08 10:56
Fixed, available from version 0.6.30

**Closed** 2024-04-12 20:38 UTC
Labels: bug, Fixed
