### ISSUE TITLE
Being able to change the cover of the playlist 

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#4455] opened 2024-11-11 02:08 UTC
### Description

Please add the ability to change the cover image for playlists, that would be great and would give a bit of authenticity to your playlists :)

### Suggested Solution

:)

### Additional Context

Please

**Comment by Abhinavreddy-B** [comment] 2024-11-11 06:02
Duplicate of #4327

Will be coming in next release

**Closed** 2024-11-15 22:52 UTC
Labels: enhancement, implemented
