### ISSUE TITLE
The navigation bar overlaps tracks/artists etc.

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1398] opened 2024-04-06 06:08 UTC
### Steps to reproduce the bug

1. In UI settings pick Navigation bar position - bottom
2. Open any folder, Artists, songs, any playlist etc. 
3. Tracks, artists and everything in the bottom of the list are overlapped by navigation bar

![1](https://github.com/fast4x/RiMusic/assets/76595855/f35ae0f8-dfdf-453b-911b-7530c01a6a11)

![2](https://github.com/fast4x/RiMusic/assets/76595855/fafbfe24-dad3-4448-b399-47ebb3301623)

![3](https://github.com/fast4x/RiMusic/assets/76595855/33ae6867-49b8-4077-ba77-533971c638ce)

### Expected behavior

You can see everything clearly

### Actual behavior

Navigation bar overlaps content

### RiMusic version

0.6.29

### Android version

Android 13

### Additional information

Samsung Galaxy A51

**Comment by NikunjKhangwal** [comment] 2024-04-06 06:12
Duplicate of #1394

**Closed** 2024-04-06 06:43 UTC
Labels: bug
