### ISSUE TITLE
Add material you theme

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1312] opened 2024-03-30 10:37 UTC
A material you theme that takes colors from our current wallpaper would be a nice addition as it would increase coherency between apps in android versions that use material you.

Another fork of ViMusic called ViTune has this option. It is available to me even on android 11.

Screenshot: https://mark.nl.tab.digital/s/9e7obwdT7Lcimoi

**Comment by privacyfreak84** [comment] 2024-03-30 10:42
This issue in the ViTune github repo sheds additional light on this topic: https://github.com/25huizengek1/ViTune/issues/129

**Comment by sayyid5416** [comment] 2024-03-30 23:56
Duplicate of #42 #868 #256 and maybe more

**Comment by dAtA-TRoN** [comment] 2024-03-31 04:57
> Duplicate of #42 #868 #256 and maybe more 

Everyone loves 🌈colors🌈 I guess 😀.

**Comment by fast4x** [comment] 2024-04-12 06:56
Implemented, available from version 0.6.30

**Comment by sayyid5416** [comment] 2024-04-12 09:32
Wow this was unexpected. Nice

**Closed** 2024-04-12 20:23 UTC
Labels: enhancement, implemented, New Idea
