### ISSUE TITLE
Calculation error on playlist play time

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#1194] opened 2024-03-23 13:09 UTC
### Steps to reproduce the bug

1. Make a playlist
2. Idk how this happened

### Expected behavior

The total play time should be accurate based on how many songs are added in the playlist 

### Actual behavior

The play time is not accurate. Let's say that the average music length is 3 minutes. I have 200 music in a playlist, that should be more or less 600 minutes. If we convert that to hours, it should be at least 10 hours. But it says the playlist is only an hour and 3 minutes long

### Screenshots/Screen recordings

![Screenshot_2024-03-23-21-03-17-471_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/160244930/9d8cb166-97ad-41e2-9c73-99f1581dcc27)

### RiMusic version

0.6.27

### Android version

Android 13

**Comment by cMattw** [comment] 2024-03-23 13:13
![Screenshot_2024-03-23-21-12-52-324_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/160244930/1c8f01fe-8f2f-4090-9485-7f56495cf576)

I really don't know how this happened. On other playlists it works fine

**Comment by JZITNIK-github** [comment] 2024-03-23 15:55
Could you please export the playlist for me so I can reproduce it? I already fixed the bug when the songs are longer than 1 hour it did not count them but if you don't have any songs longer than 1 hour in that playlist it is probably some bug.

**Comment by fast4x** [comment] 2024-03-23 19:09
Try custom version from here https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by JZITNIK-github** [comment] 2024-03-23 19:14
@fast4x What did you change in the custom version? I've tried to figure out what is causing the problem but couldn't find it. Or in the custom version is just my previous fix?

**Comment by fast4x** [comment] 2024-03-23 19:15
Yes maybe contain your fix

**Comment by cMattw** [comment] 2024-03-24 05:43
It's still not fixed in the custom version. Here's the [exported playlist](https://drive.google.com/file/d/1FIcfb769iN2rTyKUKe6ueziMCDiOY8fL/view?usp=drivesdk). And I do not have a song with more than an hour length

**Comment by JZITNIK-github** [comment] 2024-03-24 07:30
> It's still not fixed in the custom version. Here's the [exported playlist](https://drive.google.com/file/d/1FIcfb769iN2rTyKUKe6ueziMCDiOY8fL/view?usp=drivesdk). And I do not have a song with more than an hour length

Thanks. I'll look into that.

**Comment by fast4x** [comment] 2024-03-24 08:41
@JZITNIK-github there are a lot of songs without duration...
![Screenshot_2024-03-24-09-39-35-855_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/1484476/9d65b2d5-a7fb-477f-b793-1ced82e3563b)

**Comment by JZITNIK-github** [comment] 2024-03-24 08:41
Ok, so the playlist did not have duration in a lot of songs. I fixed the playlist but still if you import it the duration will not appear because you still have the songs (without the duration) saved in cache even when you remove the existing playlist. Also I have no idea why did this even happen. Why you have songs without duration saved, this is probably some bug. @fast4x do you have any idea how to import the fixed playlist? 

Fixed playlist: [Download from MediaFire](https://www.mediafire.com/file/rx2lphxabjuedgo/new_playlist.csv/file)

**Comment by fast4x** [comment] 2024-03-24 08:52
@JZITNIK-github No, it’s the first time I’ve seen this problem, I’ll try to understand it. I saw that if I play the song anyway, the duration in the player is visible so I don’t understand why.

**Comment by JZITNIK-github** [comment] 2024-03-24 08:53
> @JZITNIK-github No, it’s the first time I’ve seen this problem, I’ll try to understand it. I saw that if I play the song anyway, the duration in the player is visible so I don’t understand why.

Yeah, I think that the duration in the player is calculated based of the contents of the song (the actual data) not values in the database.

**Comment by fast4x** [comment] 2024-03-24 08:59
Yes, of course I meant that the song has the duration in the player because it is loaded in live mode

**Comment by fast4x** [comment] 2024-03-24 09:01
Nice bug...

**Comment by cMattw** [comment] 2024-03-24 11:30
I imported the playlist from yt music. That information might help...

**Comment by cMattw** [comment] 2024-03-24 11:41
> Ok, so the playlist did not have duration in a lot of songs. I fixed the playlist but still if you import it the duration will not appear because you still have the songs (without the duration) saved in database even when you remove the existing playlist. Also I have no idea why did this even happen. Why you have songs without duration saved, this is probably some bug. @fast4x do you have any idea how to import the fixed playlist? 
> 
> Fixed playlist: [Download from MediaFire](https://www.mediafire.com/file/rx2lphxabjuedgo/new_playlist.csv/file)

I imported the fixed playlist but it's still the same ![Screenshot_2024-03-24-19-40-59-418_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/160244930/7a053e07-96f0-4538-bf08-a3d2fce6b755)

**Comment by JZITNIK-github** [comment] 2024-03-24 11:43
> I imported the playlist from yt music. That information might help...

Thanks. Do you know what the original playlist was so I can try to import it?

**Comment by cMattw** [comment] 2024-03-24 11:46
> > I imported the playlist from yt music. That information might help...
> 
> Thanks. Do you know what the original playlist was so I can try to import it?

https://music.youtube.com/playlist?list=PLAm4tzAF7APIVcRGOvlYfNemQS88aECot&si=likCC9LWoe6yJIU2

**Comment by cMattw** [comment] 2024-03-24 11:49
I made all of my playlists on yt music and imported it to rimusic. This particular playlist seems to only have that bug. The other playlists have accurate playtime and each music has duration

**Comment by JZITNIK-github** [comment] 2024-03-24 11:52
Ok I imported the playlist and it works fine so there was probably some temporary issue on the YouTube Music side while you were importing the playlist. So now we need to figure out how to fix the local database. I'll try to find a way to do that.

**Comment by JZITNIK-github** [comment] 2024-03-24 12:09
@fast4x Could you please build the custom version of the app from my [fork](https://github.com/JZITNIK-github/RiMusic)? I made it so when user imports playlist it replaces the old songs from the DB with new ones. It should fix the problem when the playlist is imported again.

**Comment by fast4x** [comment] 2024-03-24 12:47
> @fast4x Could you please build the custom version of the app from my [fork](https://github.com/JZITNIK-github/RiMusic)? I made it so when user imports playlist it replaces the old songs from the DB with new ones. It should fix the problem when the playlist is imported again.

Yes, create a merge request and i build it afternoon.

**Comment by JZITNIK-github** [comment] 2024-03-24 12:55
> Yes, create a merge request and i build it afternoon.

I don't want this in the actual app because it could slow down the app. I just want it for now so we could fix the database. Right now when you import the playlist again songs in the database are ignored if there is the same song already in DB. In my fork it replaces the old one with the new instance of the song. I think the best would be to create a custom version just for this issue where it replaces it and after the new update keep it the same as before.

**Comment by fast4x** [comment] 2024-03-24 13:09
We have the opportunity to add an option for importing the playlist. We give the possibility to make the user choose if he wants to overwrite the songs, then creates an import option with overwriting. It can also be a special menu item like Import and update so ngs...

It's nice feature...

**Comment by JZITNIK-github** [comment] 2024-03-24 13:19
> We have the opportunity to add an option for importing the playlist. We give the possibility to make the user choose if he wants to overwrite the songs, then creates an import option with overwriting. It can also be a special menu item like Import and update so ngs...
> 
> It's nice feature... 

Ok if you want it I'll implement it.

**Comment by fast4x** [comment] 2024-03-24 13:25
I can build from your fork, but maybe is a opportunity...

**Comment by JZITNIK-github** [comment] 2024-03-24 13:28
> I can build from your fork, but maybe is a opportunity...

Yeah I'll implement it the way you said.

**Comment by JZITNIK-github** [comment] 2024-03-24 16:16
@fast4x I tried to implement it but I had some really weird bugs. When I have it set to replace and try to import the same playlist again it moves all the songs from the new playlist and removes them from the first one. Maybe for now just build the custom version from my fork and I'll look more in depth to the option that users could choose if they want replacing or ignoring.

**Comment by fast4x** [comment] 2024-03-24 16:34
Ok

**Comment by fast4x** [comment] 2024-03-24 17:00
@JZITNIK-github builded and published https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by JZITNIK-github** [comment] 2024-03-24 17:03
> @JZITNIK-github builded and published https://github.com/fast4x/RiMusic/tree/master/customVersion

Thanks.

@cMattw try downloading this custom version, remove the original playlist and import it again from the YouTube Music, this should fix the problem.

**Comment by cMattw** [comment] 2024-03-25 00:21
> > @JZITNIK-github builded and published https://github.com/fast4x/RiMusic/tree/master/customVersion
> 
> Thanks.
> 
> @cMattw try downloading this custom version, remove the original playlist and import it again from the YouTube Music, this should fix the problem.

It's fixed now. Thank you very much

**Comment by cMattw** [comment] 2024-03-25 00:32
The custom version fixed the playlist play time issue. But I have encountered a new bug. It doesn't let me download songs. It just removes it from the playlist.https://github.com/fast4x/RiMusic/assets/160244930/dbddabd2-1088-410e-934e-df9c398ffd0b

I will try to export the fixed playlist and import it to the stable release

**Comment by JZITNIK-github** [comment] 2024-03-25 06:23
> The custom version fixed the playlist play time issue. But I have encountered a new bug. It doesn't let me download songs. It just removes it from the playlist.
> https://github.com/fast4x/RiMusic/assets/160244930/dbddabd2-1088-410e-934e-df9c398ffd0b
> 
> I will try to export the fixed playlist and import it to the stable release
> 

Yeah, if it's possible just try to wait for the next update. In the next update downloading should be fixed.

**Comment by fast4x** [comment] 2024-03-26 23:16
@JZITNIK-github  this is fixed?

**Comment by JZITNIK-github** [comment] 2024-03-27 00:55
> @JZITNIK-github  this is fixed?

The downloading should be fixed in a new release where the inserting is ignoring and not replacing the song from DB. In my fork there is a bug that I was talking about earlier but in another release everything should be fixed.

**Comment by fast4x** [comment] 2024-03-27 06:01
Perfect, thanks for details.

**Comment by JZITNIK-github** [comment] 2024-03-30 09:00
@cMattw Is the downloading fixed in the newest version?

**Comment by cMattw** [comment] 2024-03-31 01:45
> @cMattw Is the downloading fixed in the newest version?

yes, it is fixed now. Thank you very much

**Closed** 2024-04-05 20:56 UTC
Labels: bug, Fixed

**Comment by jetlagg3d** [comment] 2024-05-31 22:40
Hi, I'm actually having the same bug after importing from YouTube music.

**Comment by fast4x** [comment] 2024-05-31 22:45
update version
