### ISSUE TITLE
Random songs added to song list (not queue) and app crashes on launch

### ISSUE THREAD

**Issue by madeleine313** [fast4x/RiMusic#4936] opened 2024-12-17 10:57 UTC
### Version of RiMusic

0.6.64 from izzyondroid f-droid repos

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

After first launching the app since update 0.6.64, 9000 random songs had been added to my song list (not the queue).
The next day (today), the app now just instantly crashes on launch.

### What was your expectation?

Not having random songs added to my songs, and the application no crashing.

### What more can you tell us? (Optional)

Take care of yourself, thanks for your work and help

**Comment by twistios** [comment] 2024-12-17 16:21
The "random songs get added to your songs list" problem is based on that the "hidden songs" feature was broken, that is the songs unknown to you are the hidden songs. This problem is fixed in the custom version that was published on the telegram group.

The crash is probably caused by the new "space indicator" for cache and download size. This bug is also fixed in the custom version.

So both these problems are fixed and the fixes will be released in the next update.

**Comment by twistios** [comment] 2024-12-17 16:39
You can try if the custom version published on github works: https://github.com/fast4x/RiMusic/tree/master/customVersion

**Closed** 2024-12-21 19:35 UTC
Labels: bug
