### ISSUE TITLE
Visibility of already added songs on the Add to playlist window

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1615] opened 2024-04-23 07:00 UTC
### Description

As I previously mentioned on 3rd point of the issue #676 sometimes while adding songs I wonder if I already have that added on certain playlists. So I had these two ideas I'll be sharing below.

### Suggested Solution

When adding songs to playlist with `Add to playlist` in the window the playlist/s that already consists that song should look different from the other playlists. Maybe keep other playlists highlighted and fade the one/s that already has the song.
![Concept of highlighting](https://github.com/fast4x/RiMusic/assets/85461823/ac7d4c71-5fc3-421a-9e9a-eacdf5532ec5)

### Alternatives

Or…How about adding [ - ] and [ + ] there instead:
![- and +](https://github.com/fast4x/RiMusic/assets/85461823/0d52652b-87cb-4ae5-a743-997f7eda115f)

Sorry for bad editing…but you get the idea. Additionally if you keep a **"Open playlist"** button as well with those that'll be even great. User will be able to check the playlists in easier way. Won't have to go through multiple pages, then scroll to find playlists. 

### Additional Context

Btw I think 1-5 points of the issue that I mentioned on description are needed for better user experience. I really hope you'll implement some of those soon. Especially 1 and 4.

**Comment by dAtA-TRoN** [comment] 2024-04-23 07:52
![Screenshot_2024-04-23-09-47-52-40_f9ee0578fe1cc94de7482bd41accb329-01.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/21381c94-3d52-403b-a14e-a269f2bedaf7)

I believe we've discussed this before. I suggested approaching it like YouTube with checkboxes. Nonetheless, however it's ultimately implemented, it's nice to see this point revisited.

**Comment by sayyid5416** [comment] 2024-04-23 07:53
Duplicate of #852

**Comment by dAtA-TRoN** [comment] 2024-04-23 08:01
> I personally dislike how it's on YouTube.

Why? It's simple and effective I guess.

**Comment by fast4x** [comment] 2024-04-23 10:40
> ![Screenshot_2024-04-23-09-47-52-40_f9ee0578fe1cc94de7482bd41accb329-01.jpeg](https://private-user-images.githubusercontent.com/71184627/324743591-21381c94-3d52-403b-a14e-a269f2bedaf7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Njg5OTMsIm5iZiI6MTcxMzg2ODY5MywicGF0aCI6Ii83MTE4NDYyNy8zMjQ3NDM1OTEtMjEzODFjOTQtM2Q1Mi00MDNiLWExNGUtYTI2OWYyYmVkYWY3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMDM4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGFlMjE4MTJhYTM0NmNhYjNiMWI4ZDE4ZWI3NjA4YTk2ZGU2ZGEzYzZjMGM1ZTc0OWE3MzdlNGI0NjcyNDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6N9ymq2nP02HwanozKQw371PbgrPLedVLUyAYAgdsWA)
> 
> I believe we've discussed this before. I suggested approaching it like YouTube with checkboxes. Nonetheless, however it's ultimately implemented, it's nice to see this point revisited.

MUCH YT like...

**Comment by fast4x** [comment] 2024-04-23 10:41
@AnyoneMouse so you like a search field in playlists list?

**Comment by dAtA-TRoN** [comment] 2024-04-23 10:54
> If yes. What I meant was just mean how Go to album works. An additional button beside each list name to open that playlist from the list.

OOOoooh NOW I see... -Sound interesting.

**Comment by fast4x** [comment] 2024-04-23 10:59
> > @AnyoneMouse so you like a search field in playlists list?
> 
> No.
> 
> And are you talking about this part?
> 
> > > Additionally if you keep a "Open playlist" button as well with those that'll be even great. User will be able to check the playlists in easier way. Won't have to go through multiple pages, then scroll to find playlists.
> 
> If yes. What I meant was just mean how `Go to album` works. An additional button beside each list name to open that playlist from the list.

ok

**Comment by fast4x** [comment] 2024-04-23 20:32
Added icon to open playlist from playlists list, available from version 0.6.32

**Comment by aneesh1122** [comment] 2024-04-23 20:43
> Added icon to open playlist from playlists list, available from version 0.6.32

Have you also added an indicator to indicate that the song is already present in a playlist?

Like in Spotify this green checkmark indicates that the song is already in a playlist
![Screenshot_2024-04-24-02-10-32-843_com.spotify.musix.png](https://github.com/fast4x/RiMusic/assets/45353488/36a67612-0db2-4140-9c13-198ca92d6546)


And then when the list of playlists appear in YouTube there is a check mark to indicate to which playlists that song is already present



I think this is the main concern of this opened issue.

**Comment by fast4x** [comment] 2024-04-23 22:43
Before there are other priorities, I'm sorry.

**Comment by fast4x** [comment] 2024-04-26 16:12
> @fast4x another idea just popped up in my mind. I would like if there was a button on the player to open playlist (If the song has been played from any playlist) of the currently playing song. **On the player menu.** Not talking about playlist list this time.

Create a new ticket for this...

**Closed** 2024-04-26 16:11 UTC
Labels: enhancement, implemented
