### ISSUE TITLE
Randomizer on Artist Tab Redirects to Last Visited Tab Instead of Random Artist Main Page

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1479] opened 2024-04-11 13:28 UTC
### Steps to reproduce the bug

1. Navigate to the Artist Tab.

2.  Tap on the randomizer icon (dice icon) located on the Artist Tab.

### Expected behavior

After tapping the randomizer icon, the user should be redirected to a randomly selected artist's main page.

### Actual behavior

Instead of being redirected to a random artist's main page every time, the user is redirected to the last visited tab of the artist, whether it be Songs, Albums, Singles, or Library. This behavior persists even after restarting the app.

Please be aware that sometimes, the user may still be redirected to the artist's main page if it was the last visited tab, but this can't be considered dependable.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/71184627/7a845c51-00c1-48b0-837c-36854d06afac

### RiMusic version

0.6.29

### Android version

Android 13

### Additional information

This behavior can be confusing and detracts from the user experience. It is expected that tapping the randomizer icon would lead to a random artists' main page, rather than consistently redirecting to the last visited tab of a specific artist. Please consider changing this behavior so that tapping the randomizer icon always redirects to a random artist's main page.

**Comment by dAtA-TRoN** [comment] 2024-04-11 15:30
> This bug is **not due to the randomizer** feature. I've noticed it **before randomizer existed** as well.
> 
> Whenever I `open an Artists page` and `tap on another tab` (Songs, Albums, Singles, Library) there and then when I `go back to Artists tab or wherever I was before` then `again open any artist`s page **I see** it in **the last tab**.
> Meaning if last time I opened the Singles tab on an Artist page then the next time I open an Artists page it'll redirect to Singles tab instead of **Overview**.

Right, you observed that well. I've already submitted a fairly comprehensive report on it as well. Yes, these two threads probably belong together. The issue is that the GitHub app is either buggy, or fast4x can somehow hide reports that he wants to postpone, so I can't link it here right now.

**Comment by fast4x** [comment] 2024-04-11 15:43
Fixed navigation tab in artist page and optimized dice feature, available from version 0.6.30

**Comment by dAtA-TRoN** [comment] 2024-04-11 15:46
> Yeah. I have seen few of my issues getting hidden. I wonder why actually though.

As I said, I think it's either fast4x or the app. Maybe it's not like that on the desktop interface. I haven't checked 🙃🤷🏻‍♂️.

**Comment by dAtA-TRoN** [comment] 2024-04-11 15:52
> Fixed navigation tab in artist page and optimized dice feature, available from version 0.6.30

"Fixed already? No way! Are you kidding me?"

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/cbfaf17d-66d3-47f6-8a59-a9fd582d19e5)

**Comment by dAtA-TRoN** [comment] 2024-04-11 15:58
> I only use Android so idk either. I really hope GitHub is not buggy because I think lots of issues has been hidden.

Perhaps it's even more insidious, and GitHub isn't actually glitchy at all. Instead, it deliberately conceals issues because it no longer deems older reports significant 😱😁.

**Comment by fast4x** [comment] 2024-04-11 15:59
> > Fixed navigation tab in artist page and optimized dice feature, available from version 0.6.30
> 
> "Fixed already? No way! Are you kidding me?"
> 
> ![proxy-image(1).gif](https://private-user-images.githubusercontent.com/71184627/321698325-cbfaf17d-66d3-47f6-8a59-a9fd582d19e5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTE0NzEsIm5iZiI6MTcxMjg1MTE3MSwicGF0aCI6Ii83MTE4NDYyNy8zMjE2OTgzMjUtY2JmYWYxN2QtNjZkMy00N2Y2LThhNTktYTlmZDU4MmQxOWU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE1NTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzdjODM4OWMyZTg3NTdiMjYwYTIwNzNkOGE2NmMyMTgxMDA0ODRhZmI2ZTc0YmM4ZDg3NjU4NjNkZGUwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v5rpMukId0Sqmx7SFG37HN9kuaVejNyXgYCR-_xJFd4) [ ![proxy-image(1).gif](https://private-user-images.githubusercontent.com/71184627/321698325-cbfaf17d-66d3-47f6-8a59-a9fd582d19e5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTE0NzEsIm5iZiI6MTcxMjg1MTE3MSwicGF0aCI6Ii83MTE4NDYyNy8zMjE2OTgzMjUtY2JmYWYxN2QtNjZkMy00N2Y2LThhNTktYTlmZDU4MmQxOWU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE1NTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzdjODM4OWMyZTg3NTdiMjYwYTIwNzNkOGE2NmMyMTgxMDA0ODRhZmI2ZTc0YmM4ZDg3NjU4NjNkZGUwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v5rpMukId0Sqmx7SFG37HN9kuaVejNyXgYCR-_xJFd4) ](https://private-user-images.githubusercontent.com/71184627/321698325-cbfaf17d-66d3-47f6-8a59-a9fd582d19e5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTE0NzEsIm5iZiI6MTcxMjg1MTE3MSwicGF0aCI6Ii83MTE4NDYyNy8zMjE2OTgzMjUtY2JmYWYxN2QtNjZkMy00N2Y2LThhNTktYTlmZDU4MmQxOWU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE1NTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzdjODM4OWMyZTg3NTdiMjYwYTIwNzNkOGE2NmMyMTgxMDA0ODRhZmI2ZTc0YmM4ZDg3NjU4NjNkZGUwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v5rpMukId0Sqmx7SFG37HN9kuaVejNyXgYCR-_xJFd4) [ ](https://private-user-images.githubusercontent.com/71184627/321698325-cbfaf17d-66d3-47f6-8a59-a9fd582d19e5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTE0NzEsIm5iZiI6MTcxMjg1MTE3MSwicGF0aCI6Ii83MTE4NDYyNy8zMjE2OTgzMjUtY2JmYWYxN2QtNjZkMy00N2Y2LThhNTktYTlmZDU4MmQxOWU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE1NTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzdjODM4OWMyZTg3NTdiMjYwYTIwNzNkOGE2NmMyMTgxMDA0ODRhZmI2ZTc0YmM4ZDg3NjU4NjNkZGUwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v5rpMukId0Sqmx7SFG37HN9kuaVejNyXgYCR-_xJFd4)

I would never allow myself to tease you, it came simple based on the info you wrote, so I think I’ve solved it.

**Comment by fast4x** [comment] 2024-04-11 16:01
![giphy](https://github.com/fast4x/RiMusic/assets/1484476/7105f48c-6962-4f69-a39c-efc0648f3ebd)

**Comment by dAtA-TRoN** [comment] 2024-04-11 16:05
> I would never allow myself to tease you, it came simple based on the info you wrote, so I think I’ve solved it.

![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/f3c335c3-1c06-432b-8680-1d410e2a39f7)

Oh, you old charmer!

**Comment by fast4x** [comment] 2024-04-11 16:20
![giphy (6)](https://github.com/fast4x/RiMusic/assets/1484476/d702e09b-c519-478e-aa93-4aede0944bde)

**Comment by fast4x** [comment] 2024-04-11 16:21
> > > I only use Android so idk either. I really hope GitHub is not buggy because I think lots of issues has been hidden.
> > 
> > 
> > Perhaps it's even more insidious, and GitHub isn't actually glitchy at all. Instead, it deliberately conceals issues because it no longer deems older reports significant 😱😁.
> 
> Seems like lots of issues has been hidden. So I don't think fast4x did that because I can't imagine him having that much spared time to select consider and postpone that many issues. I've found 14 issues like that already.

You said right, I see them all I have a huge list of tickets. You don’t see them?

**Comment by dAtA-TRoN** [comment] 2024-04-11 16:23
> Seems like lots of issues has been hidden. So I don't think fast4x did that because I can't imagine him having that much spared time to select consider and postpone that many issues. I've found 14 issues like that already.

Of course, my apologies for the mix-up! Here's the English translation:

I also don't believe he would do that. It's just a notion in my quirky mind. So dear fast4x, if you're reading this, could you perhaps share your thoughts briefly so that we can find sleep again in the future?

**Comment by fast4x** [comment] 2024-04-11 16:25
> > Seems like lots of issues has been hidden. So I don't think fast4x did that because I can't imagine him having that much spared time to select consider and postpone that many issues. I've found 14 issues like that already.
> 
> I also don't believe he would do that. It's just a notion in my quirky mind. So dear fast4x, if you're reading this, could you perhaps share your thoughts briefly so that we can find sleep again in the future?

As I said before I don’t hide tickets, I see them all, if you don’t see them I have to understand why. How many do you see?

**Comment by fast4x** [comment] 2024-04-11 16:26
i see this 
![2024-04-11_18h26_02](https://github.com/fast4x/RiMusic/assets/1484476/c9f2bd07-6a04-4204-bf75-a3fb3139cdc4)

**Comment by fast4x** [comment] 2024-04-11 16:29
and in bottom page this

![2024-04-11_18h29_03](https://github.com/fast4x/RiMusic/assets/1484476/535c4918-d3d9-4bbc-b579-a52302902c8a)

**Comment by fast4x** [comment] 2024-04-11 16:31
If you have a filter in the top page, remove it
![2024-04-11_18h30_34](https://github.com/fast4x/RiMusic/assets/1484476/9807a7d9-32ca-45e1-a849-6718992e357b)

**Comment by fast4x** [comment] 2024-04-11 16:33
I'll check

**Comment by aneesh1122** [comment] 2024-04-11 16:34
> i see this ![2024-04-11_18h26_02](https://private-user-images.githubusercontent.com/1484476/321709726-c9f2bd07-6a04-4204-bf75-a3fb3139cdc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTM0MDksIm5iZiI6MTcxMjg1MzEwOSwicGF0aCI6Ii8xNDg0NDc2LzMyMTcwOTcyNi1jOWYyYmQwNy02YTA0LTQyMDQtYmY3NS1hM2ZiMzEzOWNkYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTYzMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODdhNWYwZDc1ODViZjFlMjA4NzcwNzNmNjVlZGYzNjU3Y2NhNGQ2M2RmZjMxM2M5MDA0NzRmYWIxY2Y3NWU1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j6JwLpKuUeOTQ19u7mxZyUR0a9RoP2H439maSkDb4zc)

there are many issues which are fixed but not closed which resulted in having too many open issues. if you have fixed any issue(like this one) you should close them too.

**Comment by dAtA-TRoN** [comment] 2024-04-11 16:37
> As I said before I don’t hide tickets, I see them all, if you don’t see them I have to understand why. How many do you see?

I'm seeing 68 open cases in the app, so it seems like the app isn't showing everything. But beyond that, it's acting quite strangely because threads often disappear out of nowhere, only to reappear later. I thought maybe it could be a way for you to sometimes hide things for clarity's sake. But thanks for clearing that up. FINALLY GETTING SOME SLEEP AGAIN 😩!!!

**Comment by fast4x** [comment] 2024-04-11 16:38
> > > > Seems like lots of issues has been hidden. So I don't think fast4x did that because I can't imagine him having that much spared time to select consider and postpone that many issues. I've found 14 issues like that already.
> > > 
> > > 
> > > I also don't believe he would do that. It's just a notion in my quirky mind. So dear fast4x, if you're reading this, could you perhaps share your thoughts briefly so that we can find sleep again in the future?
> > 
> > 
> > As I said before I don’t hide tickets, I see them all, if you don’t see them I have to understand why. How many do you see?
> 
> I made a little list of some issues that I can't see without searching them via link. I searched from around 1280-latest issues. And found these issues that aren't visible. 1287, 1292, 1296, 1300, 1301, 1302, 1304, 1306-1309, 1312, 1321, 1329, 1347. After that I didn't find any other issue that isn't visible.

I see them all in order of number, i'll check for close if 

> > I'll check
> 
> Okay! Ask us anything if you need help we will do what we can.

Yes, if you can help me with the ticket for close it, thanks

**Comment by dAtA-TRoN** [comment] 2024-04-11 16:39
> I occasionally use these filters. I'm sure this problem isn't because of filters.

Yeah, me too 🤔.

**Comment by dAtA-TRoN** [comment] 2024-04-11 16:52
![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/656a9ab1-64fb-46cf-9ad9-ed247ecf9e46)

Generally speaking, the app is just shit 🤷🏻‍♂️.

**Comment by dAtA-TRoN** [comment] 2024-04-11 17:02
To fast4x:

Just a quick last-minute suggestion: when navigating within a tab, like the Artist tab, if you end up back on the last page when going back, currently you're stuck within that tab. Wouldn't it be cooler if you could still go one step further back to return to your set default page? If you haven't set a specific default page, it should still behave as mentioned initially. Did that make sense?

**Comment by dAtA-TRoN** [comment] 2024-04-11 17:17
> I didn't understand this part.

In the next RiMusic update, fast4x has made a change so that the last tab of a set of tabs is no longer mistakenly replaced by the default page. Now, the last (or first, depending on whether you're just entering the tab or already a few pages in and going back) page of a tab set is finally the real last (or first 🤯) page. However, you end up stuck on the first page, and the back button (or gesture) doesn't do anything anymore. Personally, I think it would be better if, when you have a default page set, you could go back one more time to land back on your default page. Is it now understandable?

**Comment by fast4x** [comment] 2024-04-11 18:16
This is fixed in the next version

**Comment by dAtA-TRoN** [comment] 2024-04-11 18:40
Sorry, I guess I did a poor job of explaining this 😅.

**Comment by dAtA-TRoN** [comment] 2024-04-11 18:54
> No. You did good. It's just I was unaware about that new improvement.

And what do you say about what I wrote?

**Comment by dAtA-TRoN** [comment] 2024-04-11 19:14
> Okay what I got from all that was what you want is when you're on a page and use back button/gesture you want that to lead back to previously visited (may it last or first) tab instead of default tab. 
> If that's correct then I'd like that as well. Because this is more convenient anyway.

![ZomboDroid_11042024090800.jpg](https://github.com/fast4x/RiMusic/assets/71184627/2ee45bbc-7c3e-430f-87b6-669d002ec4d6)

Now quite simply: if you haven't set a 'default page', you'll only get as far as the green line (which is good and right). However, if, for example, I've set the library (as shown in the picture) as my 'default page', then I want to be able to get there with the back button, so back beyond the green line, thus also switching the tab from Artist to Library.

**Comment by dAtA-TRoN** [comment] 2024-04-11 20:03
Then I'll just say nothing more 👀💧.

**Comment by dAtA-TRoN** [comment] 2024-04-11 20:25
![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/9d6a92f5-a4b7-4b50-bf4e-16a4880f555b)

**Comment by dAtA-TRoN** [comment] 2024-04-12 09:00
Wooooow, nice work Mr. Anymous.

**Comment by fast4x** [comment] 2024-04-12 09:08
Good job, I’ll try to understand why they are hidden since I do not hide anything

**Closed** 2024-04-12 20:21 UTC
Labels: bug, Fixed

**Comment by fast4x** [comment] 2024-04-13 07:57
Thank you, I have taken note of what you wrote, I have no idea of the cause of the problem. I see all the tickets so I don’t realize if the normal user doesn’t see some of them. Maybe it’s better to create a discussion and continue by. Thanks again for your time.
