### ISSUE TITLE
"Play next" and "Enqueue" functions don't work 

### ISSUE THREAD

**Issue by AumKalyanpur** [fast4x/RiMusic#2308] opened 2024-06-15 10:27 UTC
### Steps to reproduce the bug

1. Open app
2. Start playing any song 
3. Long press on another song
4. Click the enqueue button
5. Check the queue to see if the song was added
6. Long press another song again
7. Click the play next button
8. Check the queue again to see if the song was added

### Expected behavior

The second song which has been added to the queue should be added to the queue

### Actual behavior

The song which was supposed to be added to the queue is not added and the queue remains unchanged

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/53939710/8d62af4b-d19d-40e9-8914-b0e54afa0d33

### Logs

No crash

### RiMusic version

v0.6.39 

### Android version

Android 12

### Additional information

The queue function works in ViMusic but when I try to add to queue in Rimusic it doesn't add it to the queue at all. I tried logging into piped too. The device I'm using is an unrooted samsung galaxy tab a7.

**Comment by AumKalyanpur** [comment] 2024-06-15 10:29
Sorry. I drafted up this issue report this morning and finished and submitted it just now. (I have adhd brain) And I just checked the open issues tab and someone else has reported this issue 2 hours ago :(. Sorry

**Comment by dAtA-TRoN** [comment] 2024-06-15 11:26
Well, you can still post your video down here 🤷🏻‍♂️😁.

**Comment by Ao1Pointblank** [comment] 2024-06-15 13:13
Duplicate of #2203 (first mention of this error)
Also mentioned in other duplicates:
#2224
#2252
#2289
#2296
#2306
#2308

**Comment by Plut0ishere** [comment] 2024-06-15 16:30
> Do you have enabled Exclude songs with duration limit?

nothing really happened with it on or off and play next/enqueue still won't work

**Comment by fast4x** [comment] 2024-06-15 16:52
I'm building a custom version, try it soon please

**Comment by fast4x** [comment] 2024-06-15 17:10
https://github.com/fast4x/RiMusic/tree/master/customVersion
Try custom version

**Comment by fast4x** [comment] 2024-06-15 17:28
Fixed, available from version 0.6.40, but can download now the custom version with bug fixed.
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Plut0ishere** [comment] 2024-06-15 21:16
> Fixed, available from version 0.6.40, but can download now the custom version with bug fixed. https://github.com/fast4x/RiMusic/tree/master/customVersion

thanks dude, keep up the great work 🫶

**Comment by AumKalyanpur** [comment] 2024-06-19 15:21
Thank you so much mate. The app is just absolutely fantastic. Thanks so much :D

**Closed** 2024-06-21 19:40 UTC
Labels: bug, Fixed
