### ISSUE TITLE
New Appicon

### ISSUE THREAD

**Issue by kavi-00** [fast4x/RiMusic#661] opened 2024-02-10 17:16 UTC
### Description

Hey I love this player. Only thing bothers is the app icon. 

### Suggested Solution

If the same icon is little bit centered and having more padding from border will be good

**Comment by fast4x** [comment] 2024-02-10 17:32
@ikanakova what you think about this?

**Comment by faustaahmad** [comment] 2024-02-10 17:56
Duplicate of #393 
Basically same suggestion as mine, just different wording
I dont bother to open up for it despite that its been changed already
Just need more padding/margin or any it's called, but ikanakova changed the logo instead :'
I do respect any decision, it's just ... yeah. Dont wanted to bother for it anymore

**Comment by ikanakova** [comment] 2024-02-10 23:33
I improved the margin around the launcher icon a bit (see pull request #665), but I can't add more margin because [Google](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) recommends "Use a logo that's at least 48x48 dp." And this is already less than 48 in height.

**Comment by fast4x** [comment] 2024-02-11 15:15
Implemented, available from version 0.6.22

**Closed** 2024-02-16 17:12 UTC
Labels: enhancement, implemented
