### ISSUE TITLE
Blurry art on Android mini player

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#4429] opened 2024-11-09 23:25 UTC
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play a song
3. Use the miniplayer

### Submit a video

![Screenshot_20241110_002019](https://github.com/user-attachments/assets/ba44b916-0eb2-49d5-98b8-1b49282c8992)

### What was your expectation?

The artwork should be high quality

### What more can you tell us? (Optional)

I use a Samsung Galaxy S22 Ultra with the latest update. Before version 0.6.59, I did not have this issue.

**Comment by Donald-Win** [comment] 2024-11-10 00:54
Duplicate of [4393](https://github.com/fast4x/RiMusic/issues/4393#issue-2645205048)

Issue solved in next version

**Closed** 2024-11-15 22:51 UTC
Labels: bug, Fixed
