### ISSUE TITLE
Repeat songs

### ISSUE THREAD

**Issue by Radtrix** [fast4x/RiMusic#3609] opened 2024-09-08 22:25 UTC
### Steps to reproduce the bug

1. Play a song
2. Turn off device 
3. If device is turned off, two songs (a and b) will play, then it replays them, then it goes to the next two (c and d) then it repeats them, then goes on.

Let the letters represent the song order:
A , B , A , B , C , D , C , D , E , ...

### Expected behavior

It should just play the next song over and over again...

### Actual behavior

It repeats two songs before moving onto the next set.

### Screenshots/Screen recordings

I can't screen record with my phone turned off :/

### RiMusic version

0.6.51

### Android version

Android 14

### Additional information

All battery optimization is turned off. Wifi can be on or off too, glitch still happens.

**Comment by PH554** [comment] 2024-09-09 01:09
This is also happening to me! After I listen to two songs, suddenly, I go back to two previous songs repeating the one I had already seen.

**Comment by twistios** [comment] 2024-09-09 16:49
One version of the bug was fixed before (for example see #3355) but it is still present, I also did a report (#3534).
I think it could be related to using headphones with skipping button.

**Comment by Radtrix** [comment] 2024-09-10 18:17
I think you might be right, if I dont touch anything that changes position of the song, the glitch does not occurr as often. ..

**Comment by aneesh1122** [comment] 2024-09-30 11:36
try latest custom version and see if it's fixed

**Comment by Radtrix** [comment] 2024-09-30 13:50
Sorry, I don't know how to go to the latest custom version... unless you are talking about the release where he said nothing was changed, cause that still doesn't work.

**Comment by twistios** [comment] 2024-09-30 14:35
> Sorry, I don't know how to go to the latest custom version... unless you are talking about the release where he said nothing was changed, cause that still doesn't work.

https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Radtrix** [comment] 2024-09-30 16:52
Yeah, after listening to music for a while it started repeating the songs as described previously

**Comment by aneesh1122** [comment] 2024-09-30 16:54
> Yeah, after listening to music for a while it started repeating the songs as described previously

Songs are repeating in the custom version too?

**Comment by Radtrix** [comment] 2024-09-30 16:55
Yes, it said custom in the version when they repeated

**Comment by Radtrix** [comment] 2024-09-30 16:56
I will try and recreate it, but it happened after like 2h of listening to music, so i did something ..

**Comment by aneesh1122** [comment] 2024-09-30 16:57
> I will try and recreate it, but it happened after like 2h of listening to music, so i did something ..

Maybe your queue got over and it started over. I don't know. Try to recreate the bug

**Comment by Radtrix** [comment] 2024-09-30 21:49
So all I do is play any song, skip forward four songs, then it skips back 2 songs then replays that...

**Comment by aneesh1122** [comment] 2024-09-30 21:54
> So all I do is play any song, skip forward four songs, then it skips back 2 songs then replays that...

Is it also happening in the custom version?

Well, it's hard to fix this bug when only some users are facing this problem.

A guy I know isn't having this problem anymore with this custom version.

Maybe it will be fixed slowly for other devices too.

**Comment by aneesh1122** [comment] 2024-09-30 21:55
Which mobile are you using?

**Comment by Radtrix** [comment] 2024-09-30 22:16
I'm using an s22

**Comment by aneesh1122** [comment] 2024-09-30 22:26
> I'm using an s22

Looks like you'll have to use the essential player. 

The only way to fix this bug is to gift @fast4x a samsung s22 so that he can test the bugs since in his mobile this bug doesn't exist 😂

**Comment by Radtrix** [comment] 2024-09-30 22:28
Well i think you can use an emulator to simulate it

**Comment by Radtrix** [comment] 2024-09-30 22:34
Let's hope i don't doxx myself...
https://github.com/user-attachments/assets/651888a6-8af3-4268-a509-e67c29536b6f

**Comment by aneesh1122** [comment] 2024-09-30 22:38
> Let's hope i don't doxx myself...
> https://github.com/user-attachments/assets/651888a6-8af3-4268-a509-e67c29536b6f
> 
> 

This is the same problem I had which got fixed like 2-3 updates ago.

Let's see if fast can fix yours too.

Some people's bug got fixed so there's definitely an improvement.

**Comment by Radtrix** [comment] 2024-09-30 22:40
Lol the all mighty fast has a lot of power!
I just can't take the fixed label off the ticket...

**Comment by twistios** [comment] 2024-10-01 06:08
> This bug occurs only when you turn off the screen or put the app in the background.
> 
> @twistios is it possible in an emulator?

Putting in background definitively, turning of the screen should also work I think (there is a button for the power button).
But one needs to remember that some bugs/weird behavior only happen on the custom android versions of specific vendors.

**Comment by fast4x** [comment] 2024-10-01 06:20
Have tried latest custom version?

**Comment by knighthat** [comment] 2024-10-01 20:06
It's normal for me. I'm using version 0.6.52 on Android 14

https://github.com/user-attachments/assets/b20a5d9f-b0cc-4ba7-a7ed-84fa3a22ef61

**Comment by Radtrix** [comment] 2024-10-01 23:25
Oh weird, just figured out the same thing happens even when I am logged in... 

https://github.com/user-attachments/assets/4ad09986-ae8b-475d-9d26-b904c9e9a3ec

**Comment by fast4x** [comment] 2024-10-01 23:28
try latest custom version please

**Comment by Radtrix** [comment] 2024-10-01 23:29
I believe I am...
![Screenshot_20241001_192903](https://github.com/user-attachments/assets/76215434-59b0-4b41-bc00-baf74a2f40dd)

**Closed** 2024-10-04 23:13 UTC
Labels: bug, Fixed

**Comment by Radtrix** [comment] 2024-10-05 16:37
It still happens lol, will I just have to live with it is I am seemingly the only person experiencing it?

**Comment by twistios** [comment] 2024-10-05 17:57
@Radtrix have you tried 0.6.55?

**Comment by Radtrix** [comment] 2024-10-05 18:00
Yeah i am on 0.6.55 right now, but i just realized when ever i go to the about page it crashes... so I cant send ss

**Comment by fast4x** [comment] 2024-10-05 18:32
enable debug in miscellaneous settings restart app, go about, after crash go again to miscellaneous settings copy crash log and paste here.

**Comment by Radtrix** [comment] 2024-10-05 18:41
2024-10-05T14:01:00.164:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:261) 
	 android.content.res.Resources.getValue(Resources.java:1513) 
	 v7.b.d0(SourceFile:43) 
	 a.b.l(SourceFile:195) 
	 com.google.crypto.tink.shaded.protobuf.o0.h(SourceFile:484) 
	 j8.p.F(SourceFile:833) 
	 g8.l.g(SourceFile:71) 
	 f0.b.g(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 g8.m.o(SourceFile:58) 
	 f0.b.h(SourceFile:44) 
	 f0.b.o(SourceFile:9) 
	 K.n0.e(SourceFile:144) 
	 f0.b.f(SourceFile:44) 
	 f0.b.e(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.g(SourceFile:269) 
	 f0.b.g(SourceFile:52) 
	 j7.h.b(SourceFile:937) 
	 j7.h.a(SourceFile:228) 
	 W7.G.e(SourceFile:449) 
	 f0.b.f(SourceFile:44) 
	 F.P.g(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:23) 
	 X.t0.t(SourceFile:109) 
	 X.r0.a(SourceFile:508) 
	 K0.a0.doFrame(SourceFile:34) 
	 K0.Y.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1688) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1154) 
	 android.view.Choreographer.doFrame(Choreographer.java:1070) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:9063) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-10-05T14:41:31.423:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:261) 
	 android.content.res.Resources.getValue(Resources.java:1513) 
	 v7.b.d0(SourceFile:43) 
	 a.b.l(SourceFile:195) 
	 com.google.crypto.tink.shaded.protobuf.o0.h(SourceFile:484) 
	 j8.p.F(SourceFile:833) 
	 g8.l.g(SourceFile:71) 
	 f0.b.g(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 g8.m.o(SourceFile:58) 
	 f0.b.h(SourceFile:44) 
	 f0.b.o(SourceFile:9) 
	 K.n0.e(SourceFile:144) 
	 f0.b.f(SourceFile:44) 
	 f0.b.e(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.g(SourceFile:269) 
	 f0.b.g(SourceFile:52) 
	 j7.h.b(SourceFile:937) 
	 j7.h.a(SourceFile:228) 
	 W7.G.e(SourceFile:449) 
	 f0.b.f(SourceFile:44) 
	 F.P.g(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:23) 
	 X.t0.t(SourceFile:109) 
	 X.r0.a(SourceFile:508) 
	 K0.a0.doFrame(SourceFile:34) 
	 K0.Y.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1688) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1154) 
	 android.view.Choreographer.doFrame(Choreographer.java:1070) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:9063) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by fast4x** [comment] 2024-10-05 19:00
Ok thanks I'll check it soon

**Comment by fast4x** [comment] 2024-10-05 20:17
Update version to latest

**Comment by Radtrix** [comment] 2024-10-05 21:09
Like 0.6.55? The error happens on that version, and the custom doesn't work

**Comment by knighthat** [comment] 2024-10-05 23:30
Did you completely remove old version before install the new one?

**Comment by Radtrix** [comment] 2024-10-06 00:53
No, i will try that now though...
Okay,  so I just did it, and now I can access the about section, but I dislike deleting the app cause when ever I use a backup non of the songs download...
Oh yeah and the song repetition still happens

**Comment by knighthat** [comment] 2024-10-06 01:51
> but I dislike deleting the app cause when ever I use a backup non of the songs download...

You can always backup your song lists 

> Oh yeah and the song repetition still happens

Can you post the log here AFTER the repetition? And if you don't mind, please send me your database for further analysis

To export database: Settings > Database > Save to backup

Thank you!

**Comment by Radtrix** [comment] 2024-10-06 02:21
I back them up but when I do that when I press download all it just gets lots of songs stuck on downloading animation...

Oh and the about me page in settings is crashing again...
2024-10-05T22:15:25.870:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:261) 
	 android.content.res.Resources.getValue(Resources.java:1513) 
	 v7.b.d0(SourceFile:43) 
	 a.b.l(SourceFile:195) 
	 com.google.crypto.tink.shaded.protobuf.o0.h(SourceFile:484) 
	 j8.p.F(SourceFile:833) 
	 g8.l.g(SourceFile:71) 
	 f0.b.g(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 g8.m.o(SourceFile:58) 
	 f0.b.h(SourceFile:44) 
	 f0.b.o(SourceFile:9) 
	 K.n0.e(SourceFile:144) 
	 f0.b.f(SourceFile:44) 
	 f0.b.e(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.g(SourceFile:269) 
	 f0.b.g(SourceFile:52) 
	 j7.h.b(SourceFile:937) 
	 j7.h.a(SourceFile:228) 
	 W7.G.e(SourceFile:449) 
	 f0.b.f(SourceFile:44) 
	 F.P.g(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:23) 
	 X.t0.t(SourceFile:109) 
	 X.r0.a(SourceFile:508) 
	 K0.a0.doFrame(SourceFile:34) 
	 K0.Y.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1688) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1154) 
	 android.view.Choreographer.doFrame(Choreographer.java:1070) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:9063) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

How do I upload the db file? It isn't supported

**Comment by knighthat** [comment] 2024-10-06 14:56
You don't have to send me the database anymore. The app attempt to access something that doesn,'t exist cause it to crash

> android.content.res.Resources$NotFoundException: Resource ID #0x0

We're looking into this problem atm. If you can, please let me know all pages that this problem occurs. Thanks!

**Comment by knighthat** [comment] 2024-10-07 19:10
@Radtrix can you tell me what language were you using at the time of the crash?

**Comment by Radtrix** [comment] 2024-10-07 19:11
I am/ was using en_CA

**Comment by knighthat** [comment] 2024-10-07 19:41
Can you switch to en_US (default language pack) to see if the problem persists?

**Comment by Radtrix** [comment] 2024-10-07 20:05
I only have the option for english normal ( no suffix) or system default, as my device is eng CA it was default there,  but when I made it english no suffix it still crashes in the about page

**Comment by knighthat** [comment] 2024-10-07 20:15
thanks for the information

**Comment by Radtrix** [comment] 2024-10-14 03:37
So even in the newest version the repeat songs are happening... and sure, if i am the only one that experiences don't worry about it, but would it be possible to have the songs named in the download location as the real name instead of numbers?

**Comment by fast4x** [comment] 2024-10-14 05:44
Hold arrow icon and change order by title

**Comment by Radtrix** [comment] 2024-10-14 12:16
No no,  like in adroid/data/... folder
So then I can use something that I know works if needed and playlists will still have names

**Comment by dave-ml-xcv** [comment] 2024-11-07 09:46
Hi, this issue is in fact not fixed and has been happening for weeks on my device, to the point where I am considering moving to other apps that can actually follow a playlist/album in the background...

Redmi Note 10 Pro - MIUI 14 (also happened on 12&13)
Android 13 (also happened on 12).

The issue is as described in the original post. I use Bluetooth headphones with no forward/back controls (only play/pause) and it happens on multiple sets of headphones.

What's worse, the queue skips back *even if I manually press the Next button on the pop up notification* with the screen on. This means the Next button is also not working properly.

Thank you for the development so far and I hope this issue gets resolved as I am otherwise very impressed by te app!

**Comment by fast4x** [comment] 2024-11-07 11:51
Try latest version next Friday

**Comment by Radtrix** [comment] 2024-11-09 17:08
Still does not work. 

https://github.com/user-attachments/assets/5a6e2c79-6298-4522-9f82-8c2fb8bbef84

**Comment by dave-ml-xcv** [comment] 2024-11-12 13:07
Seems to be fixed but I only tested once with an album already cached. No songs repeated but more testing to be done before I can confirm definitely fixed.

Thanks for the update!!

**Comment by aneesh1122** [comment] 2024-12-07 04:07
Can you check if the songs are repeating in the latest update?
