### ISSUE TITLE
Default page setting does not work

### ISSUE THREAD

**Issue by Simon-Sonnleitner** [fast4x/RiMusic#3457] opened 2024-08-28 11:09 UTC
### Steps to reproduce the bug

Set Default page to playlist
Reopen app

### Expected behavior

It should automatically open in the Playlists tab

### Actual behavior

Opens in Quick Picks

### RiMusic version

0.6.49.2

### Android version

Android 14, One UI 6.1

### Additional information

It worked before 0.6.49
All other settings in Default page setting don't work either

**Comment by faustaahmad** [comment] 2024-08-28 12:00
Duplicate of #3389

**Comment by twistios** [comment] 2024-08-28 12:07
@faustaahmad maybe not a duplicate as for example in my case setting it to "songs" does not work and it always is quick picks. If you have quick picks disabled, then yes, it opens in songs.

**Comment by fast4x** [comment] 2024-08-28 13:50
Just fixed available from version 0.6.50

**Closed** 2024-08-30 21:07 UTC
Labels: bug, Fixed
