### ISSUE TITLE
Quick picks seems to be broken 

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#1553] opened 2024-04-18 10:33 UTC
### Steps to reproduce the bug

Quick picks seems to be broken in the latest updates ( or lost it's columns and rows ) 

### Expected behavior

It should ( or used to ) show 3 rows and multiple columns when slided, now it's not

### Actual behavior

It only shows the latest played song ( although it should show multiple recommendations based on the latest played song ( as configured in settings ) 
![Screenshot_20240418-142906_RiMusic](https://github.com/fast4x/RiMusic/assets/105733146/c6162239-0d19-4ac0-8523-3d352f77415a)

### RiMusic version

Latest

### Android version

Android 14

**Comment by fast4x** [comment] 2024-04-18 12:55
hi, it's just fixed in version 0.6.31 and will be available on Thursday

**Comment by NightFly88** [comment] 2024-04-18 13:55
> hallo, het is zojuist opgelost in versie 0.6.31 en zal donderdag beschikbaar zijn

Donderdag?that is today 😉

**Comment by fast4x** [comment] 2024-04-18 14:18
Is broken from YouTube Music, I'll check it

**Comment by NightFly88** [comment] 2024-04-18 14:39
I have the same problem since yesterday, 
![Screenshot_20240418_163816](https://github.com/fast4x/RiMusic/assets/163666747/769b9391-c17a-4743-a6ba-8f0969506b00)

**Comment by OrangeZXZ** [comment] 2024-04-18 14:52
same
![Screenshot_20240418_101407.jpg](https://github.com/fast4x/RiMusic/assets/104271365/1338a84f-b37e-490e-ac55-cabe14be45e4)

**Comment by VINULA2007** [comment] 2024-04-18 14:54
I wonder why it broke 
It worked fine on the first few days that I used it
Is it something with ytm?

**Comment by OrangeZXZ** [comment] 2024-04-18 14:57
> I wonder why it broke 
> It worked fine on the first few days that I used it
> Is it something with ytm? 

It certainly is the youtube api since recently they blocked some third-party yt apps and addblockers

**Comment by fast4x** [comment] 2024-04-18 17:19
It’s confirmed, YTM modified the API, so I’m checking what to do.

**Comment by VINULA2007** [comment] 2024-04-18 20:03
> It’s confirmed, YTM modified the API, so I’m checking what to do.

Looks like a hard problem to tackle

**Comment by fast4x** [comment] 2024-04-18 21:51
Applied a first fix waiting for better solution.

**Closed** 2024-04-19 21:33 UTC
Labels: bug, Fixed
