### ISSUE TITLE
Bug i do not listen music

### ISSUE THREAD

**Issue by Mendoza0G** [fast4x/RiMusic#2426] opened 2024-06-22 15:22 UTC
### Steps to reproduce the bug

The report is about a bug, it doesn't let me listen to any music, I enter an album and no music appears in all of them, if I listen to them individually it is possible but by album it doesn't let me

### Expected behavior

When I log in it won't let me listen to any songs

### Actual behavior

At the moment it won't let me listen to any songs

### Screenshots/Screen recordings

![Screenshot_20240622-092059](https://github.com/fast4x/RiMusic/assets/106029815/e2cd51c2-224a-46a5-b1e1-3d5e77262325)
![Screenshot_20240622-092115](https://github.com/fast4x/RiMusic/assets/106029815/e1c553b8-f16b-4c74-9b87-e01c963d46de)

### Logs

It won't let me, I just have to load the album, my internet is good

### RiMusic version

0.6.40

### Android version

Android 9

### Additional information

all the music I want to hear on an album won't let me

**Comment by twistios** [comment] 2024-06-22 15:26
Duplicate of https://github.com/fast4x/RiMusic/issues/2388.
The problem is because of an api-change in youtube. fast4x already knows about the problem and is working on a fix.

**Comment by fast4x** [comment] 2024-06-24 07:52
Fixed, available today from version 0.6.40.1

**Closed** 2024-06-24 10:48 UTC
Labels: bug, Fixed
