### ISSUE TITLE
Playlist, Back button

### ISSUE THREAD

**Issue by AfafAsyraf** [fast4x/RiMusic#246] opened 2023-12-18 00:10 UTC
### Steps to reproduce the bug

When creating a blank playlist it cannot be deleted. Community playlist that shown a lot of songs only showing 10/15 songs. Back button when wanna close the app is not working.

### Expected behavior

Playlist can be deleted and showing community playlist songs all of it. Back button function 

### Actual behavior

Can't be deleted the playlist and songs shown not all of them. 

### Screenshots/Screen recordings

![Screenshot_20231218-080713](https://github.com/fast4x/RiMusic/assets/154100704/5ae8f0fd-c95a-4893-a3bf-e74d55f1a341)
![Screenshot_20231218-080757](https://github.com/fast4x/RiMusic/assets/154100704/a9092859-b7f0-4eef-87cf-da3c60cbc672)
![Screenshot_20231218-080803](https://github.com/fast4x/RiMusic/assets/154100704/6d3b1a7c-848b-45e5-a206-72956fe72fe8)

### RiMusic version

0.6.13

### Android version

Android 13

**Comment by fast4x** [comment] 2023-12-18 07:44
Ok, bug confirmed.
Thanks

**Comment by fast4x** [comment] 2023-12-20 22:00
Fixed menu on empty playlist.
available from 0.6.14

**Comment by DeadSecTr** [comment] 2023-12-22 19:30
Is there any option to sort the playlist from Newest/oldest on top/bottom? 

Btw...thanks for the great app!
It works for me great!

Cheers

**Comment by fast4x** [comment] 2023-12-22 19:35
Not, but you can request this feature ☺️

**Comment by AfafAsyraf** [comment] 2023-12-22 23:32
Issues still occured. Playlist and back button still cannot go back. I have
updated to the version that you have fixed.

**Comment by fast4x** [comment] 2023-12-22 23:35
Yes I know, this ticket is not closed in fact.

**Comment by AfafAsyraf** [comment] 2023-12-22 23:38
Ahh okayy 👍🏼

**Comment by AfafAsyraf** [comment] 2023-12-23 06:02
It prompted saying there's a bug it keeps crashing and not loading music
lists.

**Comment by AfafAsyraf** [comment] 2023-12-23 06:10
After cache clean it fixed

**Comment by fast4x** [comment] 2023-12-23 13:55
Relative Back button function
Added option in setting for enable/disable Close app with back button.
Available from 0.6.15

**Comment by fast4x** [comment] 2023-12-23 13:55
> After cache clean it fixed

it fixed after? correct?

**Comment by AfafAsyraf** [comment] 2023-12-23 14:12
Still occuring after opening app. Keeps crashing and prompting app got bugs

**Closed** 2024-01-28 12:59 UTC
Labels: bug
