### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [fast4x/RiMusic#2179] opened 2024-06-04 07:02 UTC
### Steps to reproduce the bug

Your apk is built before you commit the last changes. This causes a small difference. See https://f-droid.org/en/docs/Reproducible_Builds/#vcs-info.

### Expected behavior

Reproducible

### Actual behavior

Not reproducible

### RiMusic version

0.6.37

### Android version

12

**Comment by fast4x** [comment] 2024-06-04 10:55
Hi thanks for reporting error, version/tag 0.6.37 should be ok while the one with the version/tag problem was 0.6.36.1

**Comment by linsui** [comment] 2024-06-04 11:16
Your apk is built from 8730755c0825a7af22d3b83e135cada83df3eea3. https://monitor.f-droid.org/builds/log/it.fast4x.rimusic/36#site-footer I guess you built the apk first then committed the change.

**Comment by fast4x** [comment] 2024-06-04 11:39
I’ll pay more attention to that, thank you.

**Comment by linsui** [comment] 2024-06-04 12:05
So we skip 0.6.37? Or you rebuild the apk against the tag?

**Comment by fast4x** [comment] 2024-06-04 12:09
Yes skip because I can’t build from the specific commit.

**Comment by linsui** [comment] 2024-06-04 12:11
:ok_hand:

**Comment by licaon-kter** [comment] 2024-07-30 16:24
reopen, you've tagged https://github.com/fast4x/RiMusic/releases/tag/v0.6.45.1 to f55affa8ac651175a1f426be2ab58861219e2658

but the APK was built from the older a553714caaff9e746e3fa58b29af5bf18c3ebeab ?

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7445634123#L1483

**Comment by fast4x** [comment] 2024-07-30 17:31
I have committed all code for resolving crash on 0.6.45 and builded with new tag 0.6.45.1

**Comment by licaon-kter** [comment] 2024-07-31 07:41
@fast4x are we lost in translation? :)

**Comment by fast4x** [comment] 2024-07-31 07:52
:) I added commits to created a new tag, that’s all I did.

**Comment by licaon-kter** [comment] 2024-07-31 08:17
Great... ok... and you did not build the APK from the Tag commit

why? that's up to you :)

what now? please build a NEW APK from the Tagged commit, or delete the Tag and re-Tag to the NEW commit

**Comment by fast4x** [comment] 2024-07-31 08:24
Friday I’ll do the new version, skip this version

**Comment by linsui** [comment] 2024-08-03 15:20
0.6.46 build also failed. Which commit does it build from?

**Comment by fast4x** [comment] 2024-08-03 15:28
Hi, commit is https://github.com/fast4x/RiMusic/commit/f55affa8ac651175a1f426be2ab58861219e2658

There are new things, 
- the apk file now is called app-foss-release.apk 
- and the flavour for the gradle build is Foss

Maybe that’s why you’re here?

**Comment by linsui** [comment] 2024-08-03 16:48
https://gitlab.com/linsui/fdroiddata/-/commit/740797646364550b1da1f9bdef972a69ad739905 Can you move the tag to that commit then rebuild the apk from the tag?

**Comment by fast4x** [comment] 2024-08-03 18:01
Unfortunately can't reuse existing tag with other commit. I can create a new one and rebuild apk. Would be ok?

**Comment by linsui** [comment] 2024-08-03 18:19
Please rebuild the apk from a commit. And please make sure it maych the tag next time. Maybe you can disable vcsInfo. :)

**Comment by fast4x** [comment] 2024-08-03 20:07
App rebuilded at specific commit (`34689e1768679ecd590c437c012d7ccae303293d`) and added apk in existing tag 0.6.46 I've understand what was my error...

**Comment by linsui** [comment] 2024-08-04 03:50
The apk is not reproducible. 
[it.fast4x.rimusic_47.apk.zip](https://github.com/user-attachments/files/16485379/it.fast4x.rimusic_47.apk.zip)

can you clean the cache and rebuild the apk?

**Comment by fast4x** [comment] 2024-08-04 06:21
Yes i do

**Comment by fast4x** [comment] 2024-08-04 09:13
Done and uploaded new apk

**Comment by linsui** [comment] 2024-08-04 11:58
It's still not reproducible. I have no idea...

**Comment by fast4x** [comment] 2024-08-04 12:08
Then the problem is not that, i can create a new tag but i don't know other.

**Comment by linsui** [comment] 2024-08-04 16:35
Is jdk changed?

**Comment by fast4x** [comment] 2024-08-04 16:36
No, it's same as before

**Comment by fast4x** [comment] 2024-08-07 15:23
@licaon-kter @linsui 
Maybe it fails because the gradle file contains two flavors? Can you configure the build to compile the flavour foss?

Flavour foss is default for F-Droid

**Comment by licaon-kter** [comment] 2024-08-07 15:37
> Can you configure the build to compile the flavour foss?

will try, brb

**Comment by licaon-kter** [comment] 2024-08-07 16:01
trying `foss` for https://github.com/fast4x/RiMusic/releases/tag/v0.6.46

```
==== detail begin ====
verification of APK with copied signature failed
Comparing reference APK to APK with copied signature...
Unexpected diff output:
diff -r /tmp/tmpqwr020mc/unsigned_binaries_it.fast4x.rimusic_47.binary/content/META-INF/version-control-info.textproto /tmp/tmpqwr020mc/_tmp_tmpqwr020mc_sigcp_it.fast4x.rimusic_47/content/META-INF/version-control-info.textproto
4c4
<   revision: "34689e1768679ecd590c437c012d7ccae303293d"
---
>   revision: "a68b94aa6aebaf279daa02b2d634f7b3b70bf006"
Binary files /tmp/tmpqwr020mc/unsigned_binaries_it.fast4x.rimusic_47.binary/content/assets/dexopt/baseline.prof and /tmp/tmpqwr020mc/_tmp_tmpqwr020mc_sigcp_it.fast4x.rimusic_47/content/assets/dexopt/baseline.prof differ
Binary files /tmp/tmpqwr020mc/unsigned_binaries_it.fast4x.rimusic_47.binary/content/assets/dexopt/baseline.profm and /tmp/tmpqwr020mc/_tmp_tmpqwr020mc_sigcp_it.fast4x.rimusic_47/content/assets/dexopt/baseline.profm differ
Binary files /tmp/tmpqwr020mc/unsigned_binaries_it.fast4x.rimusic_47.binary/content/classes.dex and /tmp/tmpqwr020mc/_tmp_tmpqwr020mc_sigcp_it.fast4x.rimusic_47/content/classes.dex differ
==== detail end ====
```

**Comment by fast4x** [comment] 2024-08-07 16:26
On next Friday I'll build new tag, so we can try again.

Thanks

**Comment by fast4x** [comment] 2024-08-09 20:57
New tag builded, flavour foss

**Comment by linsui** [comment] 2024-08-10 10:24
Still not reproducible... Let's check it again:

Is the apk built with jdk 17 from https://github.com/fast4x/RiMusic/releases/tag/v0.6.47? Did you clean the cache before the build? Did you run any other commands before `gradle assembleFossRelease`?

**Comment by fast4x** [comment] 2024-08-10 11:04
Yes, jdk 17, I'll clean cache and run command for rebuild apk.

**Comment by fast4x** [comment] 2024-08-10 11:13
before the command assemble.... I did not execute anything

**Comment by fast4x** [comment] 2024-08-10 11:14
The only difference from the last build played by F-Droid is the introduction of flavour foss and accrescent.

**Comment by linsui** [comment] 2024-08-10 11:15
Which OS do you use?

**Comment by fast4x** [comment] 2024-08-10 11:15
Today re build with new tag for fix any bugs.

**Comment by fast4x** [comment] 2024-08-10 11:17
> Which OS do you use?

Windows 11 with Android Studio

**Comment by linsui** [comment] 2024-08-10 11:20
Can you also try rebuilding the apk out of AS?

**Comment by fast4x** [comment] 2024-08-10 11:23
From the command line?

**Comment by linsui** [comment] 2024-08-10 11:25
Yes

**Comment by fast4x** [comment] 2024-08-10 11:25
If you agree I would test with the two apk files, could be he FDroid is compiling the flavor accrescent and finding the apk file foss, find it different?

**Comment by fast4x** [comment] 2024-08-10 11:28
I think isn't reproducible because it build accrescent and not foss...

**Comment by fast4x** [comment] 2024-08-10 11:29
> Yes

yes I'll build from command line

**Comment by linsui** [comment] 2024-08-10 11:39
https://gitlab.com/linsui/fdroiddata/-/jobs/7550604124#L427 We build the foss flavor.

**Comment by fast4x** [comment] 2024-08-10 11:45
> https://gitlab.com/linsui/fdroiddata/-/jobs/7550604124#L427 We build the foss flavor.

Would be the gradle version? I see that fdroid use 8.6 I'll check it in my project.

**Comment by linsui** [comment] 2024-08-10 11:48
It's from https://github.com/fast4x/RiMusic/blob/master/gradle/wrapper/gradle-wrapper.properties.

**Comment by fast4x** [comment] 2024-08-10 11:52
I'm confused, i don't understand why not build.

**Comment by linsui** [comment] 2024-08-10 11:58
I don't know, either... Maybe you can try rebuild [0.6.44](https://github.com/fast4x/RiMusic/releases/tag/v0.6.44) and check if the apk is changed.

**Comment by fast4x** [comment] 2024-08-10 13:41
Builded new tag v0.6.47.1 with vcsInfo disabled

**Comment by linsui** [comment] 2024-08-10 14:07
It's reproducible finally! What's changed?

**Comment by fast4x** [comment] 2024-08-10 14:12
I was convinced that I had disabled vcsInfo as you told me, but I hadn’t. I was convinced that I did it instead no!

**Comment by fast4x** [comment] 2024-08-10 14:13
Yeahhhhhhhh thanks @linsui

**Comment by fast4x** [comment] 2024-08-24 15:35
I can rebuild

**Comment by fast4x** [comment] 2024-08-24 15:40
Could it be because i added support for sdk 35 Android 15 and gradle 8.9?

**Comment by obfusk** [comment] 2024-08-24 16:10
> Clean cache and rebuild again

Did you replace the APK attached to the release? We always recommend against replacing already published APKs or tags and making a new point release instead (though we can check the APK for you before publishing that).

If so, the APK is identical to the one before. Which unfortunately means it's still not RB :/

> Could it be because i added support for sdk 35 Android 15 and gradle 8.9?

`v0.6.49` already used gradle 8.9. And neither of those is known to cause RB issues. I suspect there *could* be some issues with R8 obfuscation/shrinking (combined with compose), but I can't be sure without more testing. And builds on our end tend to be identical, so it seems likely to be some kind of build environment issue that we can't reproduce. Sadly, Android Studio is known to cause RB issues. And we already need to fix newlines because you're building on Windows.

We recently added [support for easily building APKs locally using the same recipes used by `rbtlog` but without the RB check](https://github.com/obfusk/rbtlog/issues/471), which might help in creating identical builds.

**Comment by fast4x** [comment] 2024-08-24 16:14
> > Clean cache and rebuild again
> 
> Did you replace the APK attached to the release? We always recommend against replacing already published APKs or tags and making a new point release instead (though we can check the APK for you before publishing that).
> 
> If so, the APK is identical to the one before. Which unfortunately means it's still not RB :/
> 
> > Could it be because i added support for sdk 35 Android 15 and gradle 8.9?
> 
> `v0.6.49` already used gradle 8.9. And neither of those is known to cause RB issues. I suspect there *could* be some issues with R8 obfuscation/shrinking (combined with compose), but I can't be sure without more testing. And builds on our end tend to be identical, so it seems likely to be some kind of build environment issue that we can't reproduce. Sadly, Android Studio is known to cause RB issues. And we already need to fix newlines because you're building on Windows.
> 
> We recently added [support for easily building APKs locally using the same recipes used by `rbtlog` but without the RB check](https://github.com/obfusk/rbtlog/issues/471), which might help in creating identical builds.

Ok thanks I'll check this.

**Comment by fast4x** [comment] 2024-08-24 16:15
I've rebuilded apk with new commits and new tag v0.6.49.2

**Comment by obfusk** [comment] 2024-08-24 16:29
`v0.6.49.2` is confirmed RB by our rebuilder and should show up at IzzyOnDroid with a green shield in a few hours :tada:

**Comment by fast4x** [comment] 2024-08-24 16:35
> `v0.6.49.2` is confirmed RB by our rebuilder and should show up at IzzyOnDroid with a green shield in a few hours :tada:

Thanks a lot.

**Closed** 2024-08-26 10:16 UTC
Labels: bug

**Comment by licaon-kter** [comment] 2024-09-03 11:07
:( do reopen https://monitor.f-droid.org/builds/log/it.fast4x.rimusic/54#site-footer

**Comment by obfusk** [comment] 2024-09-03 16:25
What exactly do you expect @fast4x to do here? The difference in `.prof` only is an Android toolchain bug; I suggest reporting it to Google instead, they're the only ones that can fix it. It's clearly flaky and not an issue with the APK published here as the IzzyOnDroid rebuild was perfectly fine. We have a workaround for flaky builds like that. You still don't?

**Comment by fast4x** [comment] 2024-09-03 16:56
Ok I'll try to report Google, but i don't have a workaround, can you explain me how i do exactly?

**Comment by linsui** [comment] 2024-09-03 17:20
The workaround is "try again". :)

> I'll try to report Google

Thank you very much.

**Comment by obfusk** [comment] 2024-09-03 17:21
> Ok I'll try to report Google, but i don't have a workaround, can you explain me how i do exactly?

Thanks! You can do so here: https://issuetracker.google.com/issues/new?component=192708&template=840533
Please post the link if you do.

The only workaround would be on F-Droid's end (like we have at IzzyOnDroid for these cases). There is nothing you can do here. This is not an issue with your APK like before which could be fixed with a clean build, but an issue with rebuilds being flaky (i.e. sometimes producing different results). As linsui points out, the only workaround is to build multiple times until the APK matches. Which we can do fairly easily, but F-Droid apparently still cannot.

**Comment by obfusk** [comment] 2024-09-27 21:23
```
A problem occurred configuring project ':composeApp'.
> Failed to calculate the value of task ':composeApp:compileFossDebugJavaWithJavac' property 'javaCompiler'.
   > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=22, vendor=any, implementation=vendor-specific} for LINUX on x86_64.
      > No locally installed toolchains match and toolchain download repositories have not been configured.
```

You changed the JDK version from 17 to 22, which is not available in Debian stable. At IzzyOnDroid we can build using a few different JDK versions like OpenJDK 21 (from Ubuntu `jammy`), but we can't reasonably support 22. Unlike OpenJDK 21 which is an LTS release, 22-24 are not. Debian `trixie` currently has OpenJDK 22 but is a) a moving target and b) will likely ship with OpenJDK 21 only. This makes it unsuitable for Reproducible Builds even if it likely works at the moment.

Can you please use an LTS version like 17 or 21?

**Comment by fast4x** [comment] 2024-09-28 00:23
Oh sorry, I'll try to change with 21... thanks

**Comment by fast4x** [comment] 2024-09-28 17:15
I've migrated to java 21, create a new version/tag?

**Comment by obfusk** [comment] 2024-09-28 17:41
> I've migrated to java 21, create a new version/tag?

Yeah. We'll update the recipe for our rebuilder to use OpenJDK 21 then :)

I noticed you're using `corretto`. This might be perfectly fine, but we've seen issues with alternative JDKs causing RB failures before so we generally recommend using OpenJDK (e.g. the Debian/Ubuntu/Fedora packages) to match our build environment as closely as possible. Just FYI.

**Comment by fast4x** [comment] 2024-09-28 17:58
Thanks for suggestion, I'll try directly OpenJDK.

**Comment by fast4x** [comment] 2024-09-28 22:14
Created new tag v0.6.54.1, i've builded with OpenJDK 21 (not corretto)

**Comment by obfusk** [comment] 2024-09-28 23:07
It's not RB: you forgot to commit the version code/name change (everything else is OK). Please don't modify existing APKs or tags. But do push the commit with the update. I'll patch it on our end for now.

**Comment by obfusk** [comment] 2024-09-28 23:21
With patched version code/name it's RB :)

**Comment by fast4x** [comment] 2024-09-28 23:33
Yeah thanks

**Comment by IzzySoft** [comment] 2024-10-27 20:13
Btw, 0.6.58.1 failed again. Looks like built from a dirty tree. Did you clean before build? Here's the dex diff:

```diff
--- x/classes.dex.dump	2024-10-26 23:52:10.992262468 +0200
+++ y/classes.dex.dump	2024-10-26 23:52:16.052288470 +0200
@@ -2,9 +2,9 @@
 Opened 'classes.dex', DEX version '035'
 DEX file header:
 magic               : 'dex\n035\0'
-checksum            : 0278a701
-signature           : 90bc...bc86
-file_size           : 10022620
+checksum            : ced8c9e6
+signature           : 4ccd...a4c9
+file_size           : 10022604
 header_size         : 112
 link_size           : 0
 link_off            : 0 (0x000000)
@@ -20,7 +20,7 @@
 method_ids_off      : 681476 (0x0a6604)
 class_defs_size     : 10485
 class_defs_off      : 1150484 (0x118e14)
-data_size           : 8536616
+data_size           : 8536600
 data_off            : 1486004 (0x16acb4)
 
 access_flags        : 17 (0x0011)
@@ -2025179,7 +2025179,7 @@
 |: iget-object v0, v11, Ld8/D;.B:Ljava/lang/Object;
 |: move-object v1, v0
 |: check-cast v1, LU7/h;
-|: const/16 v0, #int 8 // #8
+|: const/16 v0, #int 48 // #30
 |: move-object v2, v3
 |: move-object v3, v6
 |: move v6, v0
@@ -2052725,7 +2052725,7 @@
 |: check-cast v8, LJ8/a;
 |: const/4 v2, #int 0 // #0
 |: invoke-virtual {v11, v2}, LX/r;.r:(Z)V
-|: const v12, #float 2.01464e-38 // #00db6000
+|: const v12, #float 2.0147e-38 // #00db6180
 |: const/4 v13, #int 0 // #0
 |: iget v4, v0, Lf8/n0;.E:I
 |: iget v6, v0, Lf8/n0;.F:F
@@ -2056900,7 +2056900,7 @@
 |: move-object v7, v4
 |: check-cast v7, LJ8/a;
 |: invoke-virtual {v10, v3}, LX/r;.r:(Z)V
-|: const v11, #float 3.09945e-40 // #00036000
+|: const v11, #float 3.10483e-40 // #00036180
 |: const/4 v12, #int 0 // #0
 |: iget-object v1, v2, LU7/y;.a:LU7/v;
 |: iget v2, v0, Lf8/s0;.N:I
@@ -2423522,7 +2423522,7 @@
       registers     : 15
       ins           : 5
       outs          : 8
-      insns size    : 241 16-bit code units
+      insns size    : 234 16-bit code units
 | f8.H0.r:(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 |: check-cast v11, LD/c;
 |: check-cast v12, Ljava/lang/Number;
@@ -2423560,7 +2423560,7 @@
 |: if-nez v11, 003d // +0003
 |: goto 0042 // +0006
 |: invoke-virtual {v13}, LX/r;.W:()V
-|: goto/16 00ee // +00ae
+|: goto/16 00e7 // +00a7
 |: iget-object v11, v10, Lf8/H0;.z:Ljava/util/List;
 |: invoke-interface {v11, v12}, Ljava/util/List;.get:(I)Ljava/lang/Object;
 |: move-result-object v11
@@ -2423580,10 +2423580,6 @@
 |: invoke-virtual {v13, v11}, LX/r;.i:(Ljava/lang/Object;)Z
 |: move-result v0
 |: or-int/2addr v14, v0
-|: iget v0, v10, Lf8/H0;.A:F
-|: invoke-virtual {v13, v0}, LX/r;.d:(F)Z
-|: move-result v0
-|: or-int/2addr v14, v0
 |: iget-object v0, v10, Lf8/H0;.D:LW7/E;
 |: invoke-virtual {v13, v0}, LX/r;.i:(Ljava/lang/Object;)Z
 |: move-result v0
@@ -2423599,8 +2423595,8 @@
 |: invoke-virtual {v13}, LX/r;.R:()Ljava/lang/Object;
 |: move-result-object v0
 |: sget-object v8, LX/n;.a:LX/S;
-|: if-nez v14, 0090 // +0004
-|: if-ne v0, v8, 00a4 // +0016
+|: if-nez v14, 0089 // +0004
+|: if-ne v0, v8, 009d // +0016
 |: new-instance v14, Lb8/i;
 |: iget-object v5, v10, Lf8/H0;.E:Landroid/content/Context;
 |: iget-object v6, v10, Lf8/H0;.C:LX/X;
@@ -2423621,8 +2423617,8 @@
 |: move-result v0
 |: invoke-virtual {v13}, LX/r;.R:()Ljava/lang/Object;
 |: move-result-object v1
-|: if-nez v0, 00bd // +0004
-|: if-ne v1, v8, 00d0 // +0015
+|: if-nez v0, 00b6 // +0004
+|: if-ne v1, v8, 00c9 // +0015
 |: new-instance v6, Lb8/D;
 |: iget-object v4, v10, Lf8/H0;.I:LX/X;
 |: iget-object v5, v10, Lf8/H0;.J:LX/X;
@@ -2423640,7 +2423636,7 @@
 |: move-result-object v2
 |: invoke-static {v7}, Lv7/b;.A:(LX/X;)Z
 |: move-result v4
-|: const/16 v6, #int 8 // #8
+|: const/16 v6, #int 48 // #30
 |: const/16 v7, #int 8 // #8
 |: iget v1, v10, Lf8/H0;.A:F
 |: const/4 v3, #int 0 // #0
@@ -2423653,11 +2423649,11 @@
       catches       : (none)
       positions     : 
       locals        : 
-        0x0000 - 0x00f1 reg=10 this Lf8/H0; 
-        0x0000 - 0x00f1 reg=11 (null) Ljava/lang/Object; 
-        0x0000 - 0x00f1 reg=12 (null) Ljava/lang/Object; 
-        0x0000 - 0x00f1 reg=13 (null) Ljava/lang/Object; 
-        0x0000 - 0x00f1 reg=14 (null) Ljava/lang/Object; 
+        0x0000 - 0x00ea reg=10 this Lf8/H0; 
+        0x0000 - 0x00ea reg=11 (null) Ljava/lang/Object; 
+        0x0000 - 0x00ea reg=12 (null) Ljava/lang/Object; 
+        0x0000 - 0x00ea reg=13 (null) Ljava/lang/Object; 
+        0x0000 - 0x00ea reg=14 (null) Ljava/lang/Object; 
 
 
 access_flags        : 17 (0x0011)
@@ -2423887,7 +2423883,7 @@
 |: iget-object v9, v8, Lf8/I0;.D:LX/X;
 |: invoke-static {v9}, Lv7/b;.A:(LX/X;)Z
 |: move-result v4
-|: const/16 v6, #int 8 // #8
+|: const/16 v6, #int 48 // #30
 |: const/4 v7, #int 0 // #0
 |: iget v1, v8, Lf8/I0;.B:F
 |: const v3, #float 1.80779e+38 // #7f0800b9
```

There are entire sections only present in your build, without a corresponding par in ours, which I guess could come from artifacts left over from some previous build.

**Comment by fast4x** [comment] 2024-10-27 20:37
Sorry, i rebuild soon with clean

**Comment by IzzySoft** [comment] 2024-10-27 20:58
Thanks! But please do not replace what is already released (i.e. do not change existing tags/releases and their attachments). You can attach the APK here (simply **rename** it to `*.zip` so you can attach it), and I'll check it again, OK?

**Comment by fast4x** [comment] 2024-10-28 22:46
[app-foss-release.zip](https://github.com/user-attachments/files/17549537/app-foss-release.zip)
apk rebulded with clean and renamed in zip.

Thanks @IzzySoft

**Comment by IzzySoft** [comment] 2024-10-28 23:38
Thanks! One of our builders already confirmed that did the trick. So culprit identified to be avoided with future builds I hope :wink:

**Comment by fast4x** [comment] 2024-10-29 05:08
Yeah thanks
