### ISSUE TITLE
some songs with "inappropriate" titles being impossible to play and causing errors 

### ISSUE THREAD

**Issue by WHONEYR** [fast4x/RiMusic#2614] opened 2024-07-03 13:17 UTC
### Steps to reproduce the bug

When you play songs with titles "+18" the song doesn't play and sometimes causes a bug in the player
 (the video below is cut and speeded up to fit the 10MB size) 

https://github.com/fast4x/RiMusic/assets/168048677/0bf5e3aa-400c-4af9-af66-f2a68f71e126

### Expected behavior

the songs are playing normally and do not cause an error in the player 

### Actual behavior

the songs don't play and that warning appears in the video 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/168048677/a1631e21-8e07-4d33-bea1-d975d95b5bdd

![Screenshot_20240703_101526](https://github.com/fast4x/RiMusic/assets/168048677/5fdbe129-8cf6-4a5c-8e83-917b3465ddc7)

### RiMusic version

0.6.41

### Android version

Android 14

### Additional information

This problem has been around for a long time

**Comment by fast4x** [comment] 2024-07-03 13:44
Enable debug and paste here log, please

**Comment by fast4x** [comment] 2024-07-03 13:46
Ok, next version it's fixed with controls over number of sequential skip caused by error...

**Closed** 2024-07-05 21:46 UTC
Labels: bug, Fixed
