### ISSUE TITLE
[Feature]: dynamic system colors for android 12,13,14

### ISSUE THREAD

**Issue by jaki444** [fast4x/RiMusic#945] opened 2024-03-06 15:43 UTC
### Description

it would be nice to have android's dynamic colors that color the player a single color instead of just the choice of dynamic colors that change based on the song.

### Suggested Solution

Figure out the system color and apply it as a theme if enabled from settings

**Comment by sayyid5416** [comment] 2024-03-06 15:56
Duplicate of #256

**Closed** 2024-09-03 18:26 UTC
Labels: enhancement, implemented
