### ISSUE TITLE
Albums broken after update

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#2410] opened 2024-06-22 01:02 UTC
### Steps to reproduce the bug

1. Go to any album
2. Open it

### Expected behavior

Show the album info, songs, etc.

### Actual behavior

Shows broken Ri logo, no info, and no songs

### Screenshots/Screen recordings

![Screenshot_2024-06-21-20-59-43-88_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/35205155/2fb59b09-f4b9-46af-9df7-b3ce13faf9dc)

### RiMusic version

0.6.40

### Android version

Android 14

### Additional information

Worked fine last version, but any album I visit, not only does it not show, but in the albums menu, it shows that too, even after closing and reopening the app.

**Comment by twistios** [comment] 2024-06-22 01:04
This is a duplicate of #2388.

**Comment by RisottoDou** [comment] 2024-06-22 01:07
Having the same issue, let's hope Fast fixes this soon.

**Comment by nutzlichsein** [comment] 2024-06-22 05:50
same issue here. v0.6.39

**Comment by hashtagbrowns** [comment] 2024-06-22 06:14
same issue, when i try to edit the metadata (title, artist) of the album it just says null

**Comment by fast4x** [comment] 2024-06-22 19:13
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

**Comment by JPGuillemin** [comment] 2024-06-23 15:27
Fixed in Innertune https://github.com/Malopieds/InnerTune/commit/4a609db6d9b97b73962d3c570d757966836260ae

**Comment by fast4x** [comment] 2024-06-24 07:54
Fixed, available today from version 0.6.40.1

**Closed** 2024-06-24 10:48 UTC
Labels: bug, Fixed
