### ISSUE TITLE
Is there any way to fix suggestions

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#377] opened 2024-01-10 15:09 UTC
### Description

Both same songs in different apps

RIMusic: Music queue on Song C.U.B.A
![Screenshot_20240110-203304](https://github.com/fast4x/RiMusic/assets/120176369/75dd73e2-f279-4263-83db-834e1cb31c33)

After restarting app:
![Screenshot_20240110-203325](https://github.com/fast4x/RiMusic/assets/120176369/939c65c7-39c1-4040-a9eb-c5310ce1f659)

It is same..

YTMusic: Music queue in same song
![Screenshot_20240110-203309](https://github.com/fast4x/RiMusic/assets/120176369/6c0f4c11-6161-4a85-a3a2-8508848d0dd9)

After restarting the app:
![Screenshot_20240110-203359](https://github.com/fast4x/RiMusic/assets/120176369/269fc7d8-2af5-46a0-b820-205ff4a6ec51)

It is different...

### Suggested Solution

Ook

### Additional Context

Is there anyway to fix this

**Comment by Logan7899** [comment] 2024-01-10 15:15
I am not saying that app is trash but I am bored of listening same songs, is there any way to fix this

**Comment by ikanakova** [comment] 2024-01-10 16:08
Have you tried the start radio function? That should do a random queue based on the song, but since it recommended complete nonsense back in ViMusic (https://github.com/vfsfitvnm/ViMusic/issues/1067), I haven't used it since.

**Comment by ikanakova** [comment] 2024-01-10 16:11
Or maybe you mean something like that #153?

**Comment by Logan7899** [comment] 2024-01-10 16:21
> Or maybe you mean something like that #153?

Yes yes

**Comment by Logan7899** [comment] 2024-01-10 16:22
But in songs and playlist

**Comment by Logan7899** [comment] 2024-01-10 16:23
Otherwise the queue is same for every song wheather you refresh it

**Comment by ikanakova** [comment] 2024-01-10 16:29
> But in songs and playlist

> Otherwise the queue is same for every song

I think it's meant in #153, but you better post it there and close this. It's not a bug, the queue should still be the same unless you start radio.

**Comment by Logan7899** [comment] 2024-01-10 19:33
> > But in songs and playlist
> 
> > Otherwise the queue is same for every song
> 
> I think it's meant in #153, but you better post it there and close this. It's not a bug, the queue for playlist should still be the same unless you start radio.

But you can turn on radio everytime, sometime you just want listen songs in one tap

**Comment by ikanakova** [comment] 2024-01-10 20:23
> But you can turn on radio everytime, sometime you just want listen songs in one tap

I'm not sure if you understand what I mean by "Start radio":

![Screenshot_20240110_211541](https://github.com/fast4x/RiMusic/assets/38765251/ff037019-99e4-4e8c-b28e-d355de26c691)

Or maybe I don't understand what you mean, but your explanation certainly belongs in #153 rather than here.

**Comment by Logan7899** [comment] 2024-01-10 20:29
It is not working

**Comment by Logan7899** [comment] 2024-01-10 20:30
I clicked on start radio nothing happens

**Comment by ikanakova** [comment] 2024-01-10 21:15
For me it normally works but still suggests the same songs, but as I wrote above it's a bug from ViMusic.

**Comment by fast4x** [comment] 2024-01-11 11:39
> I clicked on start radio nothing happens 

Android version?
Link Song please ..

**Comment by Logan7899** [comment] 2024-01-11 14:36
> > I clicked on start radio nothing happens
> 
> Android version? Link Song please ..

Android version is UpsideDown cake (14)
Song is C.U.B.A by Calvin Harris
https://music.youtube.com/watch?v=vM6YnAJVDww

**Comment by fast4x** [comment] 2024-01-11 15:43
![Screenshot_2024-01-11-16-39-54-919_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/472fefee-7f47-440b-99c6-f6edac2f40aa)

My queue list after shared link from YT music to RiMusic.

I also noticed that on this song, starting the radio does not start playing the queue.

**Closed** 2024-01-15 23:54 UTC
Labels: enhancement, Not a bug
