### ISSUE TITLE
I found the error that the color of the song is put in the whole theme if you activate the theme background for the player, the dynamic mode is automatically activated, please fix that 

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#4544] opened 2024-11-16 00:22 UTC
### Version of RiMusic

0.6.60

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Please fix it:(

### What more can you tell us? (Optional)

:(

**Comment by Abhinavreddy-B** [comment] 2024-11-16 09:06
duplicate of #4540

**Comment by fast4x** [comment] 2024-11-19 22:10
Fixed, available from version 0.6.61

**Closed** 2024-11-22 23:10 UTC
Labels: bug, Fixed
