### ISSUE TITLE
Albums will not load

### ISSUE THREAD

**Issue by Skippy219** [fast4x/RiMusic#2424] opened 2024-06-22 14:45 UTC
### Steps to reproduce the bug

1. Open artists page or song player
2. Go to any album
3. None of the albums load, even the downloads. 
![Screenshot_20240622_073904](https://github.com/fast4x/RiMusic/assets/173556293/5127a722-63b5-4897-9d84-0f6eaef64803)

### Expected behavior

Everything loads quickly.

### Actual behavior

No albums or playlists load up. 

### RiMusic version

v0.6.36

### Android version

Android 13

**Comment by twistios** [comment] 2024-06-22 15:30
Possible duplicate of https://github.com/fast4x/RiMusic/issues/2388.
The first part of the problem is because of an api-change in youtube. fast4x already knows about the problem and is working on a fix.
But I was not aware that there are also problems with downloaded albums.

**Comment by Skippy219** [comment] 2024-06-22 16:13
Yea it looks like the same problem. Good to know. I made the mistake of pressing the sync button and it seems to have lost all the songs in my biggest playlist.

**Comment by fast4x** [comment] 2024-06-22 19:19
Yes it's a bug related to api changes...

**Comment by fast4x** [comment] 2024-06-24 11:25
Download latest version

**Closed** 2024-06-28 20:53 UTC
Labels: bug, Fixed
