### ISSUE TITLE
manually reorder song in playlist crashes app

### ISSUE THREAD

**Issue by spencerharmon** [fast4x/RiMusic#3414] opened 2024-08-25 17:47 UTC
### Steps to reproduce the bug

Manually reordering songs in a playlist is causing a crash after updating to v0.6.49.2. This worked in version v0.6.48, IIRC.

Steps to reproduce:

1. Have songs in playlist
2. Playlist in "position" sorting order
3. Lock icon is unlocked 
4. Touch and drag double line icon to reorder song 
5. Crash

### Expected behavior

Dragging tracks in playlist so configured reorders this track in playlist

### Actual behavior

Crash

### RiMusic version

v0.6.49.2

### Android version

android 11

**Comment by twistios** [comment] 2024-08-25 17:56
Duplicate of #3403.

**Comment by spencerharmon** [comment] 2024-08-25 17:59
Closing duplicate

**Closed** 2024-08-25 17:59 UTC
Labels: bug
