### ISSUE TITLE
Played songs are removed from the record and favorites when you listen to them. And they can also be changed from there.

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#4167] opened 2024-10-25 23:21 UTC
### Version of RiMusic

0.6.58

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. When entering the songs section 
3. When you tried to listen to songs I've already listened to

### Submit a video

https://github.com/user-attachments/assets/f1357915-0758-4fee-a873-c8d8eb1e39b4

https://github.com/user-attachments/assets/4ac4e6b9-4d60-4598-9f6c-85efc0661f22

### What was your expectation?

Smooth operation

### What more can you tell us? (Optional)

When listening to songs normally, they are removed from the registry out of nowhere and that applies to favorites 
Also not working changing song when swiping left from there

**Comment by OrangeZXZ** [comment] 2024-10-25 23:25
Could it be possible to create a custom version for this issue if it is patched?

**Comment by OrangeZXZ** [comment] 2024-10-25 23:30
Duplicate of #4160

**Comment by Ppverybig0** [comment] 2024-10-26 14:57
Same is happening with me

**Comment by fast4x** [comment] 2024-10-26 20:12
Fixed, available from version 0.6.58.1

**Comment by OrangeZXZ** [comment] 2024-10-26 20:16
>Fixed, available from version 0.6.58.1.

No custom version to keep favorites?

Okay, I will use a database that I am going to load next update.

**Comment by fast4x** [comment] 2024-10-26 20:26
Publishing...

**Closed** 2024-10-26 20:50 UTC
Labels: bug, Fixed
